### ISSUE TITLE
Changing bottom_level of manhole is not working

### ISSUE THREAD

**Issue by tudorbarascu** [QGEP/QGEP#146]
When trying to change the bottom_level field for a manhole, although the layer sees the change.. and the user can save it, the new value doesn't get saved.

**Comment by m-kuhn** [comment]
I assume this is related to the view vw_qgep_cover?

If this is indeed the case, we should add the field to the tests here and update the view appropriately
https://github.com/QGEP/datamodel/blob/master/test/test_views.py#L56

**Comment by tudorbarascu** [comment]
yes, vw_qgep_cover is the culprit

**Comment by m-kuhn** [comment]
The issue is caused by the fact that a wastewater structure can have multiple wastewater nodes attached and with an update it's not clear to which one to map it.

We have these fields present to populate an initial wastewater node when the wastewater structure is created.

Often (for manholes) it's just a single wastewater node, I think for this case it makes sense to keep the fields present.

The question is how to handle wastewater structures with multiple nodes. Should the fields be disabled? Is there a "main" node which can be shown more prominently while the other nodes are accessed via the relation editor widget...

**Comment by m-kuhn** [comment]
Added a relation editor which shall be used instead of the form fields on update (but not on insert).

Further improvements would be in the form python code to disable the appropriate tabs on insert / update.

**Comment by tudorbarascu** [comment]
It works nice, thanks!
