### ISSUE TITLE
Background color for text diagrams in GEP-Plan

### ISSUE THREAD

**Issue by andreasneumann** [QGEP/QGEP#15]
For the GEP-Plan we need to allow data-defined background color and alpha values in text diagrams.

The clean way would be to allow classification for the background color (categories and rules), however, the quicker, less expensive way would be to support rgba fill values based on an attribute value.

**Comment by 3nids** [comment]
@andreasneumann is this achieved?

**Comment by andreasneumann** [comment]
Perhaps it is too Uster-specific. Since Uster is not active on the group and others perhaps don't need it, better close the issue? Or ask Koni if he needs it?

**Comment by kfischerar** [comment]
no he doesn'tthx koni


... out of Office...
-------- Ursprüngliche Nachricht --------Von: Andreas Neumann <notifications@github.com> Datum: 01.02.17  08:45  (GMT+01:00) An: QGEP/QGEP <QGEP@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [QGEP/QGEP] Background color for text diagrams in GEP-Plan (#15) 
Perhaps it is too Uster-specific. Since Uster is not active on the group and others perhaps don't need it, better close the issue? Or ask Koni if he needs it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/QGEP/QGEP","title":"QGEP/QGEP","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/QGEP/QGEP"}},"updates":{"snippets":[{"icon":"PERSON","message":"@andreasneumann in #15: Perhaps it is too Uster-specific. Since Uster is not active on the group and others perhaps don't need it, better close the issue? Or ask Koni if he needs it?"}],"action":{"name":"View Issue","url":"https://github.com/QGEP/QGEP/issues/15#issuecomment-276592900"}}}
