### ISSUE TITLE
KEK extension: damages datamodel problems

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#153]
# Evaluation

A number of questions concerning the representation of damage in the datamodel (KEK extension)

There are two children of the table `od_damage` (no others known):
- `od_damage_manhole`
- `od_damage_channel`

They share most of their fields:
- `distance`
- `video_counter`
- `damage_reach`
- `view_parameters`
- `connection`
- `dammage_end`

Distinct fields are:
- `damage_code_manhole` / `damage_code_channel`
- `dammage_begin` / `damage_begin`

Distinct field types:
- `quantification1` is an `integer` on channel, `varchar(20)` on manhole
- `quantification2` is an `integer` on channel, `varchar(20)` on manhole
# Proposal
## Fix typos

dammage should probably be damage, that would increase the number of common fields by 1.
## Move fields to parent table
- Unless there are more children than `od_damage_manhole` and `od_damage_channel` most fields should be moved to the parent table `od_damage`.
- The two fields `damage_code_manhole` and `damage_code_channel` should be renamed to `damage_code` for consistency with e.g. `function` on `od_manhole` and `od_special_structure` which are also not suffixed by the subclass name.
## Consolidate data types

Quantification fields should be assigned the same data types or renamed to reflect the semantic difference that explains the difference in types.

**Comment by sjib** [comment]
dammage is changed to damage.
The other stuff will be discussed with the next model release of VSA-KEK (maybe 2016)

**Comment by m-kuhn** [comment]
Manually fixed the remaining occurrences and added a regression test in https://github.com/QGEP/datamodel/commit/132a294bb9e021e53e9a4a65575a27b485476a3d

**Comment by 3nids** [comment]
also incoherence: od_damage_manhole.damage_code_manhole vs od_damage_channel.channel_damage_code

**Comment by sjib** [comment]
Ok, that is a good hint to adjust the English translation:

New suggestion: od_damage_manhole.damage_code and od_damage_channel.damage_code – or different attribute names because the value lists are not the same (may be not necessary, manhole.function is also different to special_structure.function. What do you think?

 

also incoherence: od_damage_manhole.damage_code_manhole vs od_damage_channel.channel_damage_code

**Comment by 3nids** [comment]
Yes, that would be perfect. They can be named the same, they are in the children table because they point to different VL, if they were pointing to the same they would in the parent table.

So if we list things to: 

* [ ] rename `od_damage_manhole.damage_code` and `od_damage_channel.damage_code`
* [ ] define variable types for `quantification1(/2)` (integer?)
* [ ] move `connection`, `damage_reach`, `damage_begin`, `damage_end`, `distance`, `quantification1`, `quantification2`, `video_counter`, `view_parameters` to parent table (`od_damage`)
* [ ] table `qgep.vl_damage_manhole_yyy_manhole_schachtbereich` is not translated
* [ ] fix typos

@sjib does that sound correct to you?
I propose to modify the SQL creation directly, and wait for Stefan's modifications later on. What do you think?

**Comment by sjib** [comment]
Quantification: Should be text because depending on the damage_code it has a different unit. 

2.1.5 Quantifizierungen

Für jeden Code können bis zu zwei Quantifizierungen angegeben werden. Die Quantifizierungen sind

als Einzelwerte (Maximalwerte), nicht als Bandbreiten, anzugeben. Dort wo die SN EN 13508-2 eine

Quantifizierung verlangt, sollte diese wenn möglich angegeben werden. Die Masseinheit muss immer

der Norm entsprechen. Ist eine Angabe nicht sinnvoll oder nicht möglich, darf sie weggelassen werden.

Wenn SN EN 13508-2 keine Quantifizierung fordert, darf keine eingegeben werden

 

It can be e.g. 20% 

2.3.1 BAA Verformung

Dieser Code kann für alle Werkstoffe angewendet werden. Bei nicht biegeweichen Rohren mit Rissbildungen,

aufgrund von Deformationen, müssen zuerst diese Risse mit einem separaten Code beschrieben

werden.

Die Quantifizierung ist die prozentuale Reduzierung der Abmessung gegenüber der Ursprungsform:

Zum Beispiel: Rundes Rohr DN 300 mm,

Lichte Höhe noch 240 mm

Deformation = 20 %

 

or 10 mm

2.3.2 BAB Risse

Längsrisse müssen erst ab einem Verlauf von länger als 100 cm mit den Codes für Anfang und Ende

codiert werden.

Die Quantifizierung ist die Breite des Risses in mm.

 

So you have to add the unit also with the number and you cannot store this in an integer.

 

The other suggestions I will discuss with the VSA-KEK commission of the VSA.

The thing is more a didactical one: 

connection, damage_reach, damage_begin, damage_end, distance do not have the exact same definition for damage_manhole or damage_channel – see object catalog chapter 4.6 and 4.7 – often it references either to chapter 2.xx or chapter 3.xx, sometimes it is the distance from the cover or the distance from the begin of the reach. 

Database technically it has the same unit, so it would not be a problem. If you put it in the superclass, if you want to add a help file e.g. the description from the object catalog or chapter 2.xx or 3.xx you would have a very long documentation if you would alway have to say – in case of damage_manhole it is this and in case it is a damage_channel it is that.

 

quantification1, quantification2 here it is a little bit as above – quantifications always relate to the ENCode – and therefore also either chapter 2.xx or 3.xx of the norm Schadencodierung

 

video_counter, view_parameters to parent table – here I see no problems to move it.

 

So this some thoughts about it for right now.

**Comment by 3nids** [comment]
I would say that if they have different meanings, the fields should stay in the children tables

For quantifications, the unit are given in the norm (i.e. cm, °, %, etc). So, I think they must be decimal or integer. One should not write manually the unit there! Don't you think?

**Comment by 3nids** [comment]
@sjib what would be the delay to have a reply on this? cheers.

**Comment by sjib** [comment]
I talked with the VSA-KEK group. Quantification really do not need a unit, just the number. There is actually one case where quantification is not an integer: 
3.5.1 DCA Anschluss
Sohlgleiche Anschlüsse sind mit der Charakterisierung B zu beschreiben.
Die Quantifizierung 1 ist die Haltungsbezeichnung der angeschlossenen Leitung. Die Quantifizierung 2 ist die Bezeichnung des nächsten Knoten/Schachts
Here we need a string, not an integer. This case is usually not used in Switzerland, because we do not distinguish because we have the sewer network in the VSA-DSS model and do not distinguish this.

The other suggestions are ok to take the attributes to the superclass od_damage. I will include this in the coming release of VSA-KEK (mid to end 2016) - you can adapt those changes for yourself for right now with a change script.

**Comment by sjib** [comment]
Why did you change quanitifcation now to varchar instead of integer?
I just explained above, that the case where we have varchar is only for case 3.5.1 - that is not really used in Switzerland. So the trend is to go for integer in the future and kick out case 3.5.1.
https://github.com/QGEP/datamodel/commit/a1fbbad8dabd1586628291c06eafa92bf78bf25d

**Comment by 3nids** [comment]
operator is present in od_examination and od_maintenance_event. Is this expected? Shall we remove the one from examination?

**Comment by sjib** [comment]
Thanks for the hint: This looks really like a double:

The detailed definitions: examination.operator (Name of operator) – German: Untersuchung.Operateur, French: Examen.Operateur (meaning the operator of the TV camera)

This is in this case the same as: maintenance_event.operator (Operator of operating company or administration) – German: Erhaltungsereignis.Ausfuehrender (Sachbearbeiter Firma oder Verwaltung), French: Evenement_maintenance.Executant: Responsable de saisie du bureau

So I think you can skip it in the subclass examination and we will correct that with the new VSA-KEK release.

Please not, that examination.operator is really only the name of the operator (Mr. XY), and the company name is in the new relation fs_operating_company (connection to class organisation)

**Comment by 3nids** [comment]
thanks Stefan!

**Comment by 3nids** [comment]
for od_damage_channel.connection, there is this comment: 
```Kennzeichen für eine Feststellung an einer Rohrverbindung (2.1.7). Entspricht in SN EN 13508 ja = "A", nein = leer.```

@sjib can you give some explanations? Especially, what does 2.1.7 refers to?

**Comment by sjib** [comment]
2.1.7 refers to the chapter of the VSA norm. Because the VSA norm is the implementation of the EN Norm 13508 it explains how the value of the EN norm is transformed in the Swiss norm: ja equals “A”, nein equals “” (or leer/empty in words)

**Comment by 3nids** [comment]
another error: there is no entries in the dictionary table for KEK od tables.
Hence, you can't add any data.
temporary fix https://github.com/QGEP/datamodel/commit/0790613cb739ff116151eccd11da231a2bdf5f1b

**Comment by sjib** [comment]
https://github.com/QGEP/datamodel/pull/17 reflects changes - fixes should not be needed anymore afterwards - please check @3nids after successful integration in master

**Comment by 3nids** [comment]
It seems that the relation from the od_damage to od_examination has been removed.
It used to be here: https://github.com/QGEP/datamodel/blob/a1fbbad8dabd1586628291c06eafa92bf78bf25d/04_vsa_kek_extension.sql#L374
but not anymore.

Is this an error? Or can you give some explanations?

Are these changes documented somewhere? There was some changes in field names too (fs_* to fk_*). This is a bit hard to trackdown in plain SQL files....

**Comment by 3nids** [comment]
In the meantime, I put back the KEK fix file.
https://github.com/QGEP/datamodel/commit/32aba7cf3f3fe2e1f59c388e66a62f25ed888951
I used fk_examination instead of fs_* to follow other changes.

**Comment by 3nids** [comment]
@sjib any news on this?

**Comment by sjib** [comment]
Just put those relations back in - I have to check in the metadatabase why they got lost.

**Comment by sjib** [comment]
Should be solved with https://github.com/QGEP/datamodel/pull/39 04_vsa_kek_extension.sql

**Comment by sjib** [comment]
The new version of VSA-KEK places damage_begin, damage_end and distance in the subclasses as with channel_damage those fields are MANDATORY and in manhole_damage not. Do we want to solve this issue on the import / export interface or do we change that (again), as in a form you should be able to set it to MANDATORY?
