### ISSUE TITLE
User configuration

### ISSUE THREAD

**Issue by m-kuhn** [QGEP/QGEP#192]
Some of the configuration will be saved to the database.
One example is a lookup table for parameters required to calculate the replacement value (clear height, depth -> price/m).

I think it makes sense to put such data into a separate schema `qgep_config`. @3nids you have experience with dividing data into different schemas. Do you think this is a good approach for modularizing the data?

**Comment by 3nids** [comment]
Yes, I think it makes things much easier.
I would be in favor of having qgep_sys, qgep_vl, qgep_od

To me the advantages:

* easier to define access rights to login roles (per schema is easier than a set of table)
* makes the database easier to browse/read
* might be easier to do model updates and have a per-schema procedure

**Comment by m-kuhn** [comment]
Can you shortly describe the contents of `qgep_sys`. Is that the same as my `qgep_config`?

**Comment by 3nids** [comment]
I suppose: we have dictionaries, config variable, logged actions

**Comment by m-kuhn** [comment]
I think it would make sense to keep user writable tables (config) separate from others (dictionaries: *ro* after initial import, logged actions: *rw* for system)

**Comment by 3nids** [comment]
yes, maybe both config and sys

**Comment by ponceta** [comment]
:+1:  For both db lisibility and rights management, it's a blessing!

**Comment by haubourg** [comment]
On some big project, we have schema separated also by thematic / application field. 
For instance for Paris Wastewater, we have thematic schemas for reference data because those concern  different teams and it's easier to collaborate this way. 
We also have a schema  dedicated only to the  "API", only storing stored procedure and views that act as generic interfaces. something like snapPipe(), invertPipeDirection(), disconnectPipe(),  getPipe() for procedures, and simplified views to feed ORM's for third party app's 
And we also have a system schema like in QWAT for DB admin tasks like storing the versions, adding pgtap testing stuff...

**Comment by 3nids** [comment]
created an issue for table dispatch in schemas: see #391
