### ISSUE TITLE
Wastewater_node attributes not updated with vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#245]
When I update the attribute bottom_level in vw_qgep_wastewater_structure, the modifications are not registered in the upstream table. There might be a problem with the trigger on update?

**Comment by m-kuhn** [comment]
Background:
There could be multiple wastewater_nodes per wastewater_structure, so it's not unambiguous which one to update. At the moment, no wastewater_node attributes are updated.

Possible solutions:

* Define the first wastewater_node as "main_wastewater_node" (the same like we did for cover) for the 99% where there is one single node per structure.
* Ignore the fields if there is more than one wastewater_node attached to a wastewater_structure.

@urskaufmann @sjib

**Comment by sjib** [comment]
- Define the first one created as main_wastewater_node looks like a good solution. If someone wants to change the bottom_level of another wasterwater_node in the structure he has to use the subtable to do so.

- Ignoring the fields if there is more than one node is also a good solution, then you know that you have to really edit the bottom_level in the subtable and think about which one you want to update. Maybe even the better solution from my perspektive (as we do not have too many structures with more than one node)
@urskaufmann What do you think?

**Comment by urskaufmann** [comment]
In GEPView it works like that:
if you edit the wastewater-node, then it is no problem, it is clear, which node is concerned.
if you edit the cover, you can edit the bottom_level in the general tab, if there is just one node. Otherwise you have to use the subtable.
I have no main node.
Usually I do not edit the wastewater-node directly, usually I edit the wastewater-structure and related tables by the cover.
