### ISSUE TITLE
New Maintenance Event labeling in French

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#262]
I installed the actual demo project.
And now I want to create a new Maintenance event in the feature attributes from vw_qgep_reach, 
the labeling of the new maintenance tab is in French.
I looked through the issues and I didn’t find any answer.  Someone knows why?

**Comment by tudorbarascu** [comment]
Hi @kfischerar The base qgep_en.qgs project had few widgets configured with ``value_fr``. They were solved in https://github.com/QGEP/QGEP/commit/b1cfc7c4007d411622e365b3630849748b55887b but the demo data hasn't been generated since so that's why you encountered it.

You can solve it manually by going on the layer properties -> the respective fields -> click on the edit widget of the field (should be a ValueRelation widget type) and change it from ``value_fr`` to ``value_en``.

Simply copying qgep_en.qgs from master over the demo model should work also.

@m-kuhn Should the data model be auto-generated when qgep_en.qgs changes?
