### ISSUE TITLE
QGIS issue with view using st collect on 3D geometries

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#297]
On Postgis, creating a view of a collection of 3D POINTZ geometries creates a MULTIPOINT Z geometry.

![image](https://cloud.githubusercontent.com/assets/8614223/24545771/d4dd6694-1608-11e7-8d8e-6e29574918cc.png)

But on QGIS (2.18.5 and previous), selecting this view as a layer, for example 

![image](https://cloud.githubusercontent.com/assets/8614223/24545825/13916548-1609-11e7-8d1c-29c71f293147.png)

Results in a MULTIPOINT geometry instead of a MULTIPOINT Z.

And Loading options on other geom types are not proposing Z geometries.

This implies that any snapping on 2D geometries for reaches as an example will fail since layer is requiring 3D. I had almost same issue on QWAT, went on converting all my layers to 3D layers (https://github.com/qwat/QWAT/issues/74).

-> Could be subject to a QEP or be corrected to QGIS 3.

**Workaround** : Define manually in the .qgs file the Z extension for each geodata layer <3

**Comment by m-kuhn** [comment]
Does this work?

    CREATE VIEW qgep.collected_covers AS SELECT st_collect(ST_Force_3D(co.situation_geometry))::geometry(MultiPointZ, 21781) FROM qgep.od_cover co;

ST_Force3D should not be required in your case since the cover already seems to be a 3D coordinate (but it shouldn't actually be one because Z is encoded in the attribute `od_cover.level`), you probably caught a dabase model which had every geometry in 3D, that was reverted meanwhile).

@kfischerar you recently had a similar question concerning specifying the geom-type in views. `::geometry(Type, SRID)` could work for you as well.

**Comment by ponceta** [comment]
ST_Force3d was not required but ::geometry(MultiPointZ, 21781) did the trick

For `vw_qgep_wastewater_structure` I now have :
`(st_collect(co.situation_geometry) OVER (PARTITION BY ws.obj_id))::geometry(MultiPointZ, 21781) AS situation_geometry,`

Better workaround indeed.

**Comment by m-kuhn** [comment]
Thanks for the hint, ported to main repo

https://github.com/QGEP/datamodel/pull/34
