### ISSUE TITLE
Snapping features on QGIS 3 is problematic on qgep using node tool

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#330]
@3nids @m-kuhn 

On QGIS 2.99, I found that using the new snapping tool can be problematic on qgep since edition is automatically triggered for all layers.

Example : active layer is vw_qgep_wastewater_structure
snapping is in all layers 0.1m mode.

 - first click moves the reach
 - second click moves the wastewater node
 - third click moves the wastewater structure which moves again the wastewater node (update)

![snapping_qgis_3](https://user-images.githubusercontent.com/8614223/27030480-a90ea1f2-4f6c-11e7-9fb8-cd5cdb9f2aff.gif)

**Comment by ponceta** [comment]
Actual workaround : uncheck undesired layers when editing with node tool.

**Comment by 3nids** [comment]
there are some discussion about having optional limitation to selected features. We could also have a mode to restrict to current layer. What do you think?

**Comment by ponceta** [comment]
There are pros and cons... make it optional to all layers would be the best IMHO.

**Comment by m-kuhn** [comment]
* I would have expected that if the "wastewater structure" layer is selected this should be found first by the node tool. That would help a lot already I guess.

* If there are multiple snapping targets in the area, the user should be able to navigate through each one of them with a key and a tooltip should show up with something like *[layer name]: feature identifier*, as well as the geometry highlighted. This would be a new feature (but a really nice one I think ;) ).

**Comment by haubourg** [comment]
>I would have expected that if the "wastewater structure" layer is selected this should be found first by the node tool. That would help a lot already I guess.

We were thinking of setting priority snapping in the snapping option panel to adress that.

> If there are multiple snapping targets in the area, the user should be able to navigate through each one of them with a key and a tooltip should show up with something like [layer name]: feature identifier, as well as the geometry highlighted. This would be a new feature (but a really nice one I think ;) ).

Yep, that's an idea we are discussing with @wonder-sk here 
https://github.com/qwat/QWAT/issues/147  
Currently, we are reaching the QWAT budget limits for 2017, I informed Martin we probably will only fund the visual indicator for snapping type, and not yet the snapped feature priority / snapped feature selection. 
I'll try to see if we can do something with the € part.

**Comment by m-kuhn** [comment]
I'm not completely sure to understand yet though. *Snapping* for me intuitively refers to placing a node (the second click when the node is "dropped").

It seems here it's about choosing the node (and feature) which should be moved. Correct?

To me it seems like the first click (choosing the feature/node to work on) needs to take the current layer tree selection into account. That's how other editing tools like move feature work as well.

The second click (dropping the node) could be improved with a snapping priority (maybe even depending on the currently edited layer?).

Does that make sense?

**Comment by haubourg** [comment]
oops yes, sorry for the misunderstanding, I was indeed talking about which feature to snap to and not which node to grab before snapping it.. 
Now that I get it correctly, yes, using the active layer as the priority is what is expected by users.  @wonder-sk Is there any intended reason why this old behavior disappeared? 

And designing a new feature to choose which node to grab should be somewhat consistent with the feature "on which feature to snap to" and deserve a common approach.

**Comment by wonder-sk** [comment]
It should be quite easy to prioritize the active map layer when picking a node in node tool - if that will make editing easier to use... we could even think about having a switch between using all editable layers versus using just the active layer (which was always the case before).

**Comment by m-kuhn** [comment]
> It should be quite easy to prioritize the active map layer when picking a node in node tool - if that will make editing easier to use

Cool, that should help a lot!

> we could even think about having a switch between using all editable layers versus using just the active layer (which was always the case before).

Another option would be to inform the user that he is editing on a different layer by with some visual hint on the layer in the layer tree or other means, what do you think?

**Comment by wonder-sk** [comment]
> Another option would be to inform the user that he is editing on a different layer by with some visual hint on the layer in the layer tree or other means, what do you think?

Also an option, but I thought the problem here was that people have multiple layers in editing mode and at a particular moment they only want to edit one layer without having to switch editing of other layers off. So while having a visual hint may be nice, it maybe does not solve the issue...

**Comment by m-kuhn** [comment]
If I understand it correctly, the issue is related to having multiple layers in edit mode but only concerns situations where nodes overlap. So the "if multiple matches are there, prioritize active layer" logic should solve this.

Anything else is IMHO "nice to have" (in addition to the above change). Personally I think it would be nice to be able to select features from other layers without having to click on the layer tree. And some hint that this happened would make it even nicer :)

**Comment by haubourg** [comment]
I filed a ticket for the very last proposal here : 
https://issues.qgis.org/issues/17076
"Priorize active layer when picking a node with new node tool editor"

It could also be a reverse logic, like Mapinfo does, use CTRL+clic will loop around all features of every layer under the clic. We could highlight the concerned layer in the registry and the feature to give that a graphical hint about what node is really picked. 

Whatever choice we make, I think 3.0 must have it or we go into troubles...

**Comment by m-kuhn** [comment]
IMHO - priority 1: active layer first, priority 2: additionally add the logic to loop around all features

**Comment by haubourg** [comment]
@3nids @m-kuhn @wonder-sk 
Hi all, given that the feature freeze is coming fast, I would propose, if any developer has some time for it, to push Matthias's proposal of priorizing active layer for node grabing when using the node tool. I think if we don't do that, we may face a user mutinery ;-).  
@ponceta already agrees. Denis, we could push that from QWAT's funds, do you agree?

**Comment by 3nids** [comment]
that's perfect for me!

**Comment by ponceta** [comment]
+1

**Comment by m-kuhn** [comment]
@wonder-sk you would be a perfect fit for this, but I'll also find time given the high priority of this if you don't have the resources left.

**Comment by haubourg** [comment]
> @wonder-sk you would be a perfect fit for this, but I'll also find time given the high priority of this if you don't have the resources left.

That's nice! Can you estimate the task for my big project management spreasheet?

**Comment by wonder-sk** [comment]
Hi guys! If we are talking just about using active layer if there are multiple options, that should take less than half a day and I can do that this week.

If we are talking about extra logic to pick the right vertex from multiple options, we need some consensus first how to do that. My suggestion would be to have a dedicated key (e.g. Tab?) and pressing it would cycle through other possible vertices, ideally with a tooltip with layer name + feature. Or alternatively to use right-click to cycle through the options - I have seen that in PCB software.

(By the way, feature freeze has been extended again (yay!), see PSC meeting notes from this Monday)

**Comment by haubourg** [comment]
@wonder-sk Attended that it is only 1/2 a day an that we have the clearance to go for it, I propose take option 1 quickly, in case we can't achieve a consensus by the new feature freeze (thanks for the info, I missed it). 
**So go for it on behalf of QWAT, thanks very much for that! **

For the _great_ option, we have to discuss that together with the snapping discussion which is very similar and immediately follows that during an edit session. Let's maybe find a name those two clicks of the "click-click" node tool. What about : 

1- Grab a node - priority and interactive choice.  
2- Snap a node - priority and interactive choice

I like the TAB approach, but this will override the current TAB which is used to select UI elements. And this is probably something standard for accessibility. Right click is currently used to display the node editor action. @delazj @nirvn, do you have an opinion on that?


Thinking of it, I'm more and more convinced we need to have something homogeneous on all the maptools regarding active layer behavior and feature /  node interactive selection. Some use current selected feature of active layer, some first found under click in active layer, some don't bother at all about active layer.  FYI we just changed the behavior for labeling map tools, so that they focus on labels of the current active layer. This is to be merged soon in the auxiliary storage PR by @pblottiere.

**Comment by m-kuhn** [comment]
> I like the TAB approach, but this will override the current TAB which is used to select UI elements. And this is probably something standard for accessibility. Right click is currently used to display the node editor action. @DelazJ @nirvn, do you have an opinion on that?

Is it really a problem to have a different behavior of tab when a) you are in a digitizing operation and b) the focus is on the map canvas?

> I'm more and more convinced we need to have something homogeneous on all the maptools regarding

sounds good, I would prefer a solution without selection, this forces users to switch tools and do extra-clicks.

**Comment by DelazJ** [comment]
@haubourg 
> Right click is currently used to display the node editor action.

With the identifier tool right-click is used to browse the layers and features that are under the mouse, so for consistency, I'd favor using right-click also for the node tool to browse features and layers. Would need to find another way to show the node editor (i still couldn't remember why it's now only shown on demand and not automatically, be it not at the top level of the panels)
@m-kuhn 
> > I'm more and more convinced we need to have something homogeneous on all the maptools regarding

> sounds good, I would prefer a solution without selection, this forces users to switch tools and do extra-clicks.

Sorry but I fail to understand what you mean by "forces users to switch tools". Do you refer to selection of features or of layers?

The behavior of map tools with selection is really inconsistent in QGIS. I've been writing an issue report long time ago and gave up because couldn't find a behavior I can consider as the basis and identify which tool is misbehaving (split features, reshape tool, add part/ring...). The logic I would advocate for is: Like I think we do with Processing, "If there are selected features (try to) use only them (and report a failure if ever), otherwise use overlapping features".

**Comment by m-kuhn** [comment]
> Sorry but I fail to understand what you mean by "forces users to switch tools". Do you refer to selection of features or of layers?

of features. you need to switch to the selection tool if the selection is wrong.

**Comment by wonder-sk** [comment]
Active layer first: https://github.com/qgis/QGIS/pull/5149

**Comment by ponceta** [comment]
Nice thanks!

Works as expected!

@haubourg I have the start logo for homogenizing all map tools, like Trump's America, it's gonna be active layer first, let's find what's second :

![active_layer first](https://user-images.githubusercontent.com/8614223/30386102-4c4a78c0-98a9-11e7-9191-f0cc3179a7a3.png)

**Comment by ponceta** [comment]
PS: I'm a huge fan of the right click node editor
