### ISSUE TITLE
fk_main_node for od_wastewater_structure

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#349]
It could be usefull to add a _fk_main_node_ attribute to _od_wastewater_structure_ as we did for the cover. Especialy in the case of a double manhole (chambre double), it is important to define the principal node.

**Comment by m-kuhn** [comment]
If there is a "real-world logical meaning" for a primary node, I'm all in for this!

Any feedback on this, @sjib @urskaufmann

**Comment by urskaufmann** [comment]
I had till now no need to define a main node. If you have more than one node in a wastewater structure, you must look closer, if you digitize or edit. The only thing a can imagine is to define the usage (and thereby the color of the symbol) of the wastewater_structure over the main_node and the connected channel (because there is only in the table channel a field usage). Is this the problem?

**Comment by varrieta** [comment]
Yes that is the problem. The structure has wastewater and clean wastewater passing through but the VSA says that the main node should be the wastewater node.

**Comment by sjib** [comment]
I do not think we have to reflect this "main node" in the model - that is more a principle to understand how to model a wastewater_structure with two nodes and which one to connect to the channel/reach with wastewater and which one to connect with the clean water. With the [GEP Checker](https://www.vsa.ch/fr/domaines-cc/assainissement/guide-des-donnees-pgee/datachecker-pgee/) of the VSA you will find out if you connected wastewater to clean water channel and it will give you a warning (this is one of the technical rules implemented)

**Comment by urskaufmann** [comment]
In GEPView I calculated the usage of the manhole/specialstructure in a separate query. Therefore I have a ranking of the usage (wastewater  > combined_wastewater > rain_wastewater ...). It works good, as long as the outgoing channels have the same function_hierarchic. And it slows down the whole project.
If the solution is to store somewhere some extra-data, then I would prefere to store direct the usage of the wastewater_structure and not a main_node.
There is already a class Symbol (not VSA-DSS-class). Possibly a new field in this class?

**Comment by m-kuhn** [comment]
[qgep.od_wastewater_structure._usage_current exists already]( https://github.com/QGEP/datamodel/blob/2d5455f3ed39d1e2515d95b31f4cc15170168343/05_data_model_extensions.sql#L9-L12), it's mostly a matter of adjusting the triggers if the symbology is wrong.

**Comment by varrieta** [comment]
Yes that could also be a solution. I don't see any other problem than the usage of the structure.

Does it changes something from the hydrologic side (network tracking)?

**Comment by sjib** [comment]
No - it does not change anything - it should just copy the information about the usage_current to the node. Check the triggers and rules for it - usually it should be the "dirtiest" water of all pipes to that node. E.g. if you have to pipes with clean_water - the node is also clean_water. If you have a waste_water and a clean_water pipe then the node is waste_water (or can we also create mixed_water in this case? @urskaufmann).

**Comment by urskaufmann** [comment]
I tested several cases and I think it works quite good with this _usage_current. It looks not only the dirtiest water in the outgoing reaches, it first looks the function_hierachic. If the function_hierachic is not equal, then the usage_current of the most important channel sets the value. If the function_hierachic are equal (that shoud be the normal case in my opinion), then it is the dirtiest water of the outgoing channels. The status of the channels has no influence.
@ sjib: no there is no mixed_water-symbol, if there are to nodes in the wastewater_structure and the water is hydraulically separated.

**Comment by sjib** [comment]
@varrieta Please change the trigger based on the discussion.

**Comment by varrieta** [comment]
Sorry but I'm not sure to know how to adjust the trigger (and where..)

**Comment by ponceta** [comment]
The further I go, the more I'm convinced that defining the wastewater main_node is the missing link between wastewater node and the issues I get with vw_qgep_wastewater_structure.

Of course we can aggregate the geometries to get multipoint classes to mix covers and wastewater_nodes but attributes don't aggregate so easily.

**Comment by urskaufmann** [comment]
I am not sure, this is the wright issue, but I agree with @ponceta  that there is a problem with vw_qgep_wastewater_structure and that the multipoint-geometry is a problem.
Look also my post in #430  (23.6.2019). We lose data with this view!
I have discussed the problem with @m-kuhn. There should be a solution now - the sooner the better. Please add label P1.
Proposal: vw_qgep_wastewater_structure has just a 2D-singlepoint-geometry 
(remember: in VSA-DSS there is no such point-geometry defined. It is not a good idea to invent a now geometry because you can not exchange this geometry with VSA-DSS-INTERLIS).
The geometry is just used to access the data in a GIS-environment and to show a symbol in overview-planes (not detailed planes). Therefore no 3D necessary.  Snapping is to the node-layer, as today.
To show the covers in details, you have to turn on layer vw_cover. In vw_cover we have to add some attributes like _usage_current, _function_hierarchic, _ma_function, _ss_function, _ii_kind to have correct symbols in network plan (Werkplan).
Which of the covers or nodes is used for the singlepoint-geometry has to be defined. In my opinion it should by the main-cover and if there is no cover, it should be the first node (or main-node). Or the other way round (first node and if no node is defined, its the first cover).
Its importent to always be aware, that the vw_qgep_wasterwater_structure point is not the point to be e.g. exported as DXF-data, because it most not be the cover you mesure in the field.

**Comment by ponceta** [comment]
@urskaufmann is there any problem with 3D geometry?

There's a problem with the **MultiPoint** which is a false solution since aggregation is bad for attributes.

Is there a case where a wastewater_structure (from vw_qgep_wastewater_structure) has no wastewater node?

I do agree that the vw_qgep_wastewater_structure situation should be a **single point** (hopefully the main_node situation geometry which is a PointZ geometry)

**Comment by urskaufmann** [comment]
As I described the point (symbol, point to access data), there is no need for 3D in my opinion. I can live with 3D. Cover and Wastewaternodes are 3D, they have a level-attribut.
No Node: a manhole in a pump_pressure_pipe, where is a "Putzöffnung". But I agree, there are more cases with no cover.

**Comment by m-kuhn** [comment]
Implemented in https://github.com/QGEP/datamodel/pull/111
