### ISSUE TITLE
manhole_function missing - Noeud_de_conduite

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#367]
In the french VSA-SDEE mini, we can find, for the node function attribute, the value "noeud_de_conduite".

It is used for special topological nodes not reffering to a structure but that are important to materialized. Example: Three primary reaches meeting

Is there a reason it is not in the QGEP model?

**Comment by urskaufmann** [comment]
in German this is a Leitungsknoten. There is no function in the VSA-DSS because there is no specific wastewater structure just for this node. You have to place at this point, where the primary reach meet, a wastewater node (Abwasserknoten), that is connected to the channel of the main primary reach and connect the reaches to this node.
It's then the thing of the export in to VSA-DSS mini, to set the function of this point to "Leitungsknoten" or "noeud_de_conduite".

**Comment by sjib** [comment]
You can use the [VSA GEP Datachecker](https://www.vsa.ch/fr/domaines-cc/assainissement/guide-des-donnees-pgee/datachecker-pgee/) to make the transformation from VSA-DSS <-> VSA-DSS-Mini. No need to develop yourself.

**Comment by m-kuhn** [comment]
Sidenote, [ili2pg 3.10.10 supports exporting according to base models](https://github.com/claeis/ili2db/issues/46#issuecomment-341704842).
