### ISSUE TITLE
Open/View an attached file

### ISSUE THREAD

**Issue by kfischerar** [QGEP/QGEP#369]
We attached a file in feature Attributes of a Layer (vw_qgep_wastewater_structure, Tab Files). 
How is it possible to open or view the attached file for a wastewater_structure in the canvas?

**Comment by max-trolliet** [comment]
Is the file attached with its URL?  I mostly use actions in the layer to do so.

**Comment by kfischerar** [comment]
normally its a pdf or jpg including the absolut path, for example:
c:\gep\foto\blabla.jpg

**Comment by max-trolliet** [comment]
@varrieta showed me a way : open the layer properties, and in the field, set it as external ressources, and click the "use as hyperlink for the file" 

It is litteral translation from french, and might differ a little, but this allows to click on the file as an hyperlink, which will open the file.

**Comment by kfischerar** [comment]
thx for your help, i'm stll working on it, maybe we solve it on monday

**Comment by max-trolliet** [comment]
Do you need to directly open the file or the folder containing it/them? 

We could use a relation with a "file_table" with a fk to link them, and then open each specific file by specifiying "External ressource" in the fields parameter in qgis.

Otherwise, the external file could target the folder to be opened containing n files. 

There is a constraint on how we store the files though. If we want something that is working inside qgep in an automatic mode, we might need to have the user to set paths in a specific logical way to be used. (am I beeing understandable?)

**Comment by max-trolliet** [comment]
I did the view and some of the function. I'm still wondering about the od_file.class.  Is there a exploitable link between the waistwater structure and the class anywhere in the model? I did not find any and wonder how to get update that field from the view.

**Comment by max-trolliet** [comment]
Another thing : in order to retrieve the data_media using the foreign key, I tried to set up a function : 

-- ***********************
-- Retrieve fk_data_media
-- ***********************

CREATE OR REPLACE FUNCTION qgep.fk_data_media()
  RETURNS trigger AS
$BODY$

DECLARE
	_fk character varying(16);

BEGIN

  SELECT obj_id INTO _fk
  FROM qgep.od_data_media obj_id
  WHERE NEW.path = od_data_media.path;

RETURN _fk;

END;

$BODY$
  LANGUAGE plpgsql VOLATILE;

As I'm not used to write functions yet, there is someting wring in this one... If anyone could have a look at it, that would be nice. 

Moreover, where can I put all the sql I wrote for this issue?

**Comment by m-kuhn** [comment]
@max-trolliet if you create a new file with your view next to the existing ones and create a new pull request it's available for everyone and the easiest to comment and work on.

**Comment by max-trolliet** [comment]
How do we toogle linked table to edit mode when editing the "main" views? 

@m-kuhn I think you showed me a way to get od_file, and od_data_media into edit mode when editing vw_qgep_wastewater_structure by using the service. Yet this does not do the trick.

**Comment by max-trolliet** [comment]
In vw_qgep_maintenance, we use the od_file table to store the videos. Is there any need to also have a part of the form for possible other media (picture, pdf,...)  ?

**Comment by 3nids** [comment]
At the SIGE, we used it for all inspection documents: PDF reports, pictures and videos.

**Comment by max-trolliet** [comment]
Then the form should maybe be changed to have a structure closer to wastewater structure and reach.

**Comment by max-trolliet** [comment]
@sjib there is a mistake in vl_file_kind in english 
![image](https://user-images.githubusercontent.com/13679128/36195056-7c35f51e-116c-11e8-997c-d772409dc8ad.png)

**Comment by max-trolliet** [comment]
Can anyone have a look at the insert function here? I'm trying to retrieve the foreign key using the url of the new attached file... It works with a standard query with a string a string like 'C:/repertoir_data_media/repertoir_files/image.jpg'  and it works... but when I put it here and try it in qgis..... Nothing happens.

`
-- Function: qgep.vw_file_insert()

-- DROP FUNCTION qgep.vw_file_insert();

CREATE OR REPLACE FUNCTION qgep.vw_file_insert()
  RETURNS trigger AS
$BODY$
DECLARE
	_fk character varying(16);
	_path_relative character varying(100);
	_path character varying(100);

BEGIN

-- foreign key
  SELECT 
	dm.obj_id INTO _fk
  FROM 
	qgep.od_data_media dm
  WHERE 
	dm.path like COALESCE (substring(NEW._url, 1, 20),'%');

/*	
-- path
  SELECT 
	dm.path into _path
  FROM 
	qgep.od_data_media dm
  WHERE 
	dm.obj_id = _fk;
*/

-- path_relative
  SELECT 
	substring(NEW._url, char_length(_path)+1,char_length(NEW._url)) into _path_relative
  --FROM 
--	qgep.od_data_media dm
  /*WHERE 
	dm.path IN 
	(
	SELECT DISTINCT
		dm.path
	FROM qgep.od_data_media dm, qgep.vw_file

	WHERE dm.path like substring(NEW._url, 1, char_length(dm.path))
	)
	*/;


  INSERT INTO  qgep.od_file(

      obj_id,
      --class,
     --identifier,
      --kind,
      object,
      --path_relative,
      --remark,
      --last_modification,
      --fk_dataowner,
      --fk_provider,
      fk_data_media


      )
      
  VALUES     (
      qgep.generate_oid('od_file'::text),
      --NEW.class,
     -- NEW.identifier, 
     -- NEW.file_kind,
      NEW.object,
      --'qgep/code sprint 12-2017/Japan1_sm.jpg',
      --NEW.remark,
      _fk
      );
  
  RETURN NEW;
END; $BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION qgep.vw_file_insert()
  OWNER TO postgres;

`

**Comment by max-trolliet** [comment]
We did quite some improvement on this topic with Matthias yesterday. New pull request to be ready next week. 

I need some input on how we want to deal with some attributes : 

dataowner and provider : do you want to be able to insert a new feature in od_organisation if need be by creating a new feature in the view? If this is not the case, one shall have to first edit od_organisation to add the new one in order to then select it using a liste relationnal value in QGIS. Otherwise we need to have a list that allows new entities that will trigger an insert in od_organisation. 

@varrieta @kfischerar what is your feeling for this?

**Comment by varrieta** [comment]
Seems Great!
No need for me, my users add it directly in od_organisation

**Comment by sjib** [comment]
In identifier we just store the filename. For the path we have additional attributes available:
File path_relative
Data_media.path
All together gives the full path

**Comment by max-trolliet** [comment]
Yup, the full path is only in the view which will concatenate the two others.

**Comment by max-trolliet** [comment]
@sjib it seems to work for me. @kfischerar did you have the possibility to test it? I did not go on with the new schema. I think it should have been transfered in order to work as well. Can anyone confirme it?
