### ISSUE TITLE
Wastewater structures should be edited through their nodes instead of st_collect(s.p. geometries)

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#371]
**In summary:**

**Actually :** 
Edition in QGIS through vw_qgep_wastewater_structure is facing some issues:
- Moving a cover will result in a visual wastewater structure movement
  (although wastewater node stands still)
- Removing a cover will result visually as if the wastewater structure has been removed
  (although it is not the case, wastewater structure remains)
- A wastewater without a cover can't be interrogated cartographically.
- ST_COLLECT used on structure parts is potentially a point of performance leak

**Reworking intentions:**
Rework edition mechanism for vw_qgep_wastewater_structure to use wastewater node geometry:
 - Wastewater_structure edition/visualisation isn't dependant from structure parts anymore
 - Moving covers isn't linked visually to wastewater_structure
 - Snapping is done to the node element https://github.com/QGEP/QGEP/issues/406

**Edit 07.06.2018:**
Visual example:
Removing a cover makes the wastewater structure point disapear.

![suppression_couvercle](https://user-images.githubusercontent.com/8614223/37771811-0c81ec44-2dd9-11e8-9ef3-81c3161942bd.gif)

Moving a cover moves the wastewater_structure geometry.
Covers are not always in the center of the wastewater_structure.

**Comment by sjib** [comment]
Can you give specific functions of wastewater structures that this happens? 
How would you like to have it visualised?
Usually we do visualize covers separately if we have a detailed_geometry to a wastewater structure.

**Comment by varrieta** [comment]
> Some Wastewater structures have covers not directly above, it should be possible to take these into account too.

You can, by having different position for the cover and the hydraulic node. Then it is visible only if you activate the wastewater_node layer.

**Comment by ponceta** [comment]
Discharge points, and fictive wastewater structures.

**Comment by sjib** [comment]
I agree that these wastewater structures should still show up. We need at least one coordinate - either the cover coordinate or the wastewater node coordinate to have it located.
There are not ficitive wastewater structures in VSA-DSS / QGEP datamodel. We always need to have a wastewater node.
a) is it an option to make a visualisation for wastewater structures without cover and use the wastewaternode coordinate there?
b) Do you still want to distinguish the function in the visualisation, then we would need a symbol for each function

**Comment by lbartoletti** [comment]
Indeed, " fictive wastewater " is not a prerequisite, it is a legacy of an old CAD software that has no reason to be anymore.

Concerning the problem of covers and structures, we tried this workaround which seems to work:
In https://github.com/QGEP/datamodel/blob/master/view/vw_qgep_wastewater_structure.sql#L108 just take the node instead of the lid by changing co.situation_geometry to wn.situation_geometry.
For the moment we have not added the "INSTEAD OF ...", we have to go deeper into the subject.

However, it seems that this is an important subject of the QGIS project and QGEP design that we are touching. 
From a user point of view, the chamber is the central element, the cover is interesting for the topography. Especially since some rooms may not have covers (blind room - I don't know the correct English translation)
So, a change in logic is necessary.

cc @ponceta @haubourg

**Comment by m-kuhn** [comment]
Following cases exist:

 1. Structure with only cover(s) and node(s) at same position(s)
 2. Structure with cover(s) and node(s) at different position(s)
 3. Structure with only node(s)

1 should be ok already.
2 should be fine from my understanding (one can enable the wastewater node layer for visualisation)
3 definitely is an issue

I could imagine that we only change something for 3 (and use a different color in this scenario), but I'm open for solutions that change the situation for 2 as well if there is a demand for this.

**Comment by haubourg** [comment]
I agree with @lbartoletti here. We saw some caveats with using the main cover as wastewater structure:

- move cover away will lead to a chamber spatialized only where the cover is. As we already have a "cover" layer in the project, this is confusing for users that want to visualize the chamber real location. 

- If a user deletes covers and polygon structure part geometry, there is no easy way to digitize a waterstructure part easily (since it is launched by a layer action)

So I think  the project would be easier to understand with the straightforward geometry of the waterstructure, and add additional styles that will use geometry generators to display "visible main cover" for instance. I think we may also speed up the view doing this because the st_collect aggregate is probably an optimization fence currently for postgres planner.

**Comment by m-kuhn** [comment]
> So I think the project would be easier to understand with the straightforward geometry of the waterstructure (...)

with the requirement to digitize a polygon for every wastewater structure?

**Comment by haubourg** [comment]
>with the requirement to digitize a polygon for every wastewater structure?

I don't think so. You make me doubt, what would make it mandatory with the proposal?

**Comment by m-kuhn** [comment]
Because that's the way I understood "the straightforward geometry of the wastewaterstructure"

**Comment by urskaufmann** [comment]
If you lock at the sia405-model, there are several classes with point-geometry, there is the wastewater-structure-class with polygon-geometry, reaches with polylines and lots of classes without geometry.
In GIS you can display only classes with geometry directly. Therefore I had in GEPView the layer "cover" and it was clear what is displayed. The cover is the point you can directly mesure and the thing you have to find, if you are interested in a manhole or a special structure. For normal users, the building (the manhole, the special structure) is the central element, for some users (hydraulic) wastewater nodes are more important. But all of them find the information through the cover.
We once decided in the QGEP-group to call the layer not gqep_cover, but qgep_wastewater_structure. Because there is in the datamodell no superclass for just the structures that are not channels, the nomination is not very exact. In the qgep_wastewater_structure-layer should you find all the structures, that are not channels. If they have a certain extend, that is important to display, then you use the polygon-geometry in the wastewater-structure-class.
There are some cases, where you have no cover. Specially the discharge_point. Often there isn't a real building at this point (it's just the end of the channel). If you really use the whole model, then you need the discharge_point to connect it to the sector_water_body. I have never used this connection till now...
If I want to display the display-point, I use the wastewater_nodes of the discharge_points. And if there is a building (something like guide-walls) you use the polygon-geometry. Conclusion: it must be possible to add this polygon-geometryto "through" the wastewater_node .
Blind or buried manholes (= attribute "covered" in the wastewater_structure-accessibility-field) have normally a cover. You can dig them out and hopefully open this covers (otherwise that's no more a manhole = Kontrollschacht). I see now problem with these manholes. You have to add the cover as normal and the cover will symbolise the building. I have a special symbol for covered manholes.
And then there are some really rare cases, where your wastewater_structure is in a building and you have now cover, but doors. In this case you will again use the polygon_geometry anyway. But you have then no point to place the labels. I think its the point where it is not a great mistake to use a "fictive" cover.
To use the wastewater_nodes instead of the covers to display the buildings is definitely not a good idea. Wastewater_nodes are placed for hydraulic purpose, you can't see or mesure them.
I have no problem with the vw_qgep_wastewater_structure, if the channels can be removed as they have been before #420.
But I have a problem with the labels of the wastewater_structures in cases with more than one cover or wastewaternodes #356.

**Comment by urskaufmann** [comment]
Wanted to reference to 405 Channels in vw_qgep_wastewater_structure, not to 420

**Comment by sjib** [comment]
Thanks @urskaufmann for your additional info

**Comment by 3nids** [comment]
Sorry, but what is the root issue here? is it 
* vizualisation / accessing the form
* digitizing 
* else?

**Comment by ponceta** [comment]
@ All, thanks for all the constructive inputs. I've edited the head question to be clearer. Please make me know if something I missed could added to that.

**Comment by m-kuhn** [comment]
@ponceta thanks for keeping this updated. Can you add more detailed answers to @3nids questions, I think this would help a lot to get a clear picture of requirements and possible approaches.

**Comment by m-kuhn** [comment]
You highlight some important things here. I am sure we can improve the situation.

>     Moving a cover will result in a visual wastewater structure
>    (although wastewater node stands still)

Can you clarify on this point, I cannot follow.

>    Removing a cover will result visually as if the wastewater structure has been removed
>    (although it is not the case, wastewater structure remains)
>    A wastewater without a cover can't be interrogated cartographically.

In this case I think we should fallback to the wastewater node.

>    ST_COLLECT used on structure parts is potentially a point of performance leak

Let's ignore the possible performance leaks in this discussion, we can easily cache the geometry via triggers if required.

The main reason I can find above is that structures without cover are currently not visible. I think everyone agrees that those structures (e.g. discharge points) should be visualized with wastewater nodes. Where there is a difference in preference is about displaying structures with both, nodes *and* covers. @ponceta is there a strong requirement to display *nodes* and not *covers* for them?

**Comment by m-kuhn** [comment]
You highlight some important things here. I am sure we can improve the situation.

>     Moving a cover will result in a visual wastewater structure
>    (although wastewater node stands still)

Can you clarify on this point, I cannot follow.

>    Removing a cover will result visually as if the wastewater structure has been removed
>    (although it is not the case, wastewater structure remains)
>    A wastewater without a cover can't be interrogated cartographically.

In this case I think we should fallback to the wastewater node.

>    ST_COLLECT used on structure parts is potentially a point of performance leak

Let's ignore the possible performance leaks in this discussion, we can easily cache the geometry via triggers if required.

The main reason I can find above is that structures without cover are currently not visible. I think everyone agrees that those structures (e.g. discharge points) should be visualized with wastewater nodes. Where there is a difference in preference is about displaying structures with both, nodes *and* covers. @ponceta is there a strong requirement to display *nodes* and not *covers* for them?

**Comment by ponceta** [comment]
Moving a cover will result in a visual wastewater structure **movement**
(I missed a word, sorry)

I find a bit disturbing for the users to have many points mixed in the same qgis layer and editing different  object classes. (which is not the case with only covers (1 object class))
I would therefore not recommend to display both covers and nodes.

**Comment by m-kuhn** [comment]
> Moving a cover will result in a visual wastewater structure movement

It is a requirement to be able to move the whole structure, this approach allows doing this. Moving a cover on the cover layer results in a movement of the cover only. Moving an object on the wastewater structure layer moves the wasewater structure. To me this sounds semantically consistent.

> I find a bit disturbing for the users to have many points mixed in the same qgis layer and editing different object classes. (which is not the case with only covers (1 object class))

It's one of the properties of wastewater structures unofortunately, that it's not visible itself but one of the main classes, so we have to find a way to properly visualize it. Are you ok with giving the approach a test, where we have per wastewater structure either displayed *or* nodes (i.e. mixing on layer level but not on object level) and visualizing node based ones differently from cover based ones, so the user can see a visual difference of what's being rendered?

CC @varrieta , @urskaufmann , @kfischerar , @3nids

**Comment by urskaufmann** [comment]
Its just as you write Matthias: the idea is, that 90 to 95% or more of the wastewater structures (except channels) are manholes and that in most cases, people use the "Pickellochmodell" (cover-center-model): the centre of the cover is also the ww-node and is also the reach-endpoints. If you create a new wastewater structure you have not to worry about nodes and reachpoints - they are all at the same point. So it also clear, that if you move the manhole (e.g. you have better measurements of the covers), you move also the other coordinates, that are at the same place.
If you want to have different coordinates for cover, node, reach point: its possible, no problem, as Matthias described. Its a lot of (field-)work and therefore expensive to create and update all of your data in a not-cover-center-model.
I think its important, that users can edit the main-attributes, that are necessary to describe the 95% of manhole-wastewater structures, can be reached in the general tab of the form without additional mouse-clicks. 
As I wrote before, I have no problems if there are several views for the wastewater structure classes available beside the view we already have. Such views have advantages and disadvantages. I am not sure, if the user is not more confused about which layer has to be edited. There are e.g. several often used functions in class manhole and special structure (pump, manhole and so one) with same name and also same symbol. And you have to maintain several layers (forms, symbol).

**Comment by ponceta** [comment]
Ping @m-kuhn @urskaufmann @haubourg 

You will find our code proposal for edition view for wastewater structures
https://gist.github.com/ponceta/5f707c62f6f837dae2c4381a4e48d6b2

**Comment by m-kuhn** [comment]
Pull request with raw changes: https://github.com/QGEP/datamodel/pull/86

**Comment by ponceta** [comment]
Edition goes through wastewater structure, then through wastewater node and covers for additionnal points.

Wastewater_structure is now multipointz and visually attractive.

Setting dependencies correctly fixes most of my problems.

**Comment by ponceta** [comment]
@m-kuhn I'm doing some VSA reading today

![image](https://user-images.githubusercontent.com/8614223/63501013-2e8e6580-c4cb-11e9-8654-775c7dd3fa40.png)
