### ISSUE TITLE
Question about triggers and rules

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#372]
Is there a technical reason for vw_qgep_wastewater having
 - 1 rule and 3 triggers (insert / update / delete)
and vw_qgep_reach having
 - 3 rules (_return + update + delete) and 1 trigger (insert)

In terms of performance, are there any concerns here?

**Comment by haubourg** [comment]
I'm raising the question here again. From what I read, RULES where the only solution for updatable views prior to 9.1. Now, triggers are warmly recommanded because RULES implies a few caveats that can bite really hard. Rules might be a bit faster for massive updates because they are not being executed at row level, but are a complete rewrite of the original query. 
I would be in favour of switching to INSTEAD OF triggers. 

One question, If I write a PR, any objection if I replace rules by triggers in that PR ?

**Comment by haubourg** [comment]
@sjib  Not sure I get what you ask for. 

If I have to change the `UPDATE` and `INSERT` triggers in QGEP on views, is there an issue in turning RULES into triggers only on the rules I propose a change for?

**Comment by m-kuhn** [comment]
The selection in the past has mostly been driven by Postgres possibilities (at that point in time) and can be revisited.
I remember that I preferred RULES because they can be inlined by the query planner (what you write about performance with "row level").

> Now, triggers are warmly recommanded because RULES implies a few caveats that can bite really hard.
> I would be in favour of switching to INSTEAD OF triggers.

Do you have a link with more information? Do they affect us?
It's something to consider, but I'd like to have a good reasoning to base this decision on.

> One question, If I write a PR, any objection if I replace rules by triggers in that PR ?

Better keep things modular and separate.
Wholesale approaches

 * risk that pull requests are dismissed for parts of it which could be separated away
 * are harder to review and digest

**Comment by haubourg** [comment]
Hi, 


> I remember that I preferred RULES because they can be inlined by the query planner (what you write about performance with "row level").

True, I found this article that confirms how faster rules are when concerning bulk edits: https://www.cybertec-postgresql.com/en/rules-or-triggers-to-log-bulk-updates/

This won't impact everyday's GIS digitizing work, unless users do mass updates and QGIS forwards them as bulk updates to the database. Concerning the volume of data we have in pipe / network use cases on local authorities level, I suppose this is not the main bottleneck currently (though this should need to be evaluated) 

Concerning RULES vs TRIGGERS, I ear black & white. Let's not change the habits. I'll stick with the RULE system.

**Comment by signedav** [comment]
In reference to the whole Rule vs. Trigger discussion I'm checking out the problem, that on-delete-rules with multiple statements have on views. This was concerning these issues #87 and #333.

I opened a question here:
https://dba.stackexchange.com/questions/227360/delete-rule-on-view-does-not-execute-every-statement

**Comment by ponceta** [comment]
@signedav thanks!

**Comment by signedav** [comment]
Still I accept the argument for using rules for simple and rocket proof functions, because they are less code and easier to read (or the performance, if this would be the case somewhere). But I have to confess, that this "unpredictable" behavior of rules tends me to use triggers in case of doubt...
