### ISSUE TITLE
Channels in vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#405]
Channels are displayed by vw_qgep_wastewater_structure, is that normal? @m-kuhn @3nids 

![capture](https://user-images.githubusercontent.com/20111558/36209201-69845ec2-119b-11e8-837f-5dc21cef285b.PNG)

**Comment by sjib** [comment]
As channel is also a subclass of wastewater_structure, if not filtered out, they will also be listed

**Comment by varrieta** [comment]
Ok, but it wasn't the case before..

**Comment by ponceta** [comment]
There's a misconception here, I agree with @varrieta. Since vw_qgep_wastewater_structure is designed for ponctual wastewater structures edition, channels have nothing to do here (even if they are not displayed in QGIS).

I did not find any filter implemented here.

https://github.com/QGEP/datamodel/blame/74c65a844fb005a599eeb8ee91db381bf282cd9d/view/vw_qgep_wastewater_structure.sql#L104

**Comment by 3nids** [comment]
https://github.com/QGEP/datamodel/pull/71 should do the trick

**Comment by sjib** [comment]
@varrieta Is this solved? Then close please

**Comment by varrieta** [comment]
Channels are still displayed in  vw_qgep_wastewater_structure, can anyone confirm?

database version: 1.5.3

**Comment by urskaufmann** [comment]
I can confirm (database version 1.5.2). Channels are in the vw_qgep_wastewater_structure - table, but without geometry

**Comment by m-kuhn** [comment]
@olivierdalang when you have some time, can you have a look at that?

**Comment by kandre** [comment]
I confirm I have the same problem in 1.5.0 datamodel version.
Thanks for the PR.
