### ISSUE TITLE
QGIS Composer enhancement to display relationnal values in tables

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#424]
As discussed with @max-trolliet, it would be great for users to enable attribute table from relationnal database to be displayed correctly in composer

![image](https://user-images.githubusercontent.com/8614223/41718465-57905498-755d-11e8-95dd-1d4e9cc5264e.png)

![image](https://user-images.githubusercontent.com/8614223/41718455-4f3f49f2-755d-11e8-8ed0-413b0c3158b3.png)

I've not checked QGIS 3.1.X, is it in any discussion about QGIS composer enhancements? Is there already a QEP?

Actual **workaround** is reserved to sys_admin to create views with already matched, as it is in export views.

**Comment by andreasneumann** [comment]
you can use the expression "represent_value" for this. Instead of the raw data column, replace it with an expression and you should get the human readable values.

See https://qgis.org/en/site/forusers/visualchangelog30/

Requires QGIS >= 3.0

**Comment by haubourg** [comment]
@ponceta agreed, good catch here. 

@andreasneumann we are in the situation where attribute tables and forms already use value relation widgets to display translated text from codes. I believe the composer should behave the same way. This would be much more consistent from a user perspective. 

Personaly think I would like an option on field level to display the actual code. 
In the attribute table and identify results, I'd also like a tooltip on hover showing code + translation.

**Comment by andreasneumann** [comment]
I agree that probably in 99% of cases, users want the human-readable value instead of internal codes in print composer. I wouldn't mind such a change.

However, the "represent_value(datacolumn)" is a really easy workaround and works not only for value relations, but also other widgets that have an internal representation and a human readable representation. Examples are date widgets, relation_reference widgets and potentially others.

In print composer just remove the column and add the expression. Really easy.

**Comment by andreasneumann** [comment]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/884476/41720341-0c74fa9e-7563-11e8-8b5c-12d1224aa2e8.png)

**Comment by haubourg** [comment]
@andreasneumann  thanks for the workaround pointer, I wasn't aware of this new way :)

**Comment by m-kuhn** [comment]
On first sight, calling `represent_value` also for composer tables would be nice default behavior.
