### ISSUE TITLE
Altitude handling

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#429]
I'm facing issues with actual 2,5D geometries using the newly developped plugin. (see https://github.com/QGEP/QGEP/issues/406)

The idea is to set :
 - [x] wastewater_node (xy + bottom_level)
 - [x] cover (xy + level)
 - [x] reach_point (xy + level)

From 2,5D to 3D geometries and implementing triggers to maintain attribute coherency as we did in https://github.com/qwat/qwat-data-model/blob/7179cae7864773f28c61e060bf36295af0bc57ed/ordinary_data/valve/od_valve.sql#L182-L195 for example.

This was discussed previously in https://github.com/QGEP/QGEP/issues/232, https://github.com/QGEP/QGEP/issues/297

**Comment by m-kuhn** [comment]
Are users able to edit via attribute and geometry?

The main question here is, which of the two takes precedence if both are changed. And there is a certain risk, that QGIS will still have cached geometries around in some tools with Z values that are not immediately updated when the attribute changes (generally speaking, not verified).

**Comment by ponceta** [comment]
In QWAT it is the case. They don't do it at the same time since tools are different (node tools vs attribute form).

If some tools are not handling Z properly, we should fix the tools.

All we do here is give access to a second way of editing the Z through snapping.

**Comment by 3nids** [comment]
After experiencing this with QWAT, I would not redo it the same way.
These triggers brought a lot of unexpected complexity both datamodel wise (error prone).

Is the only reason is to edit Z from the node tool or your interest is more related to snapping issues?

**Comment by ponceta** [comment]
Actually I would store Z value only at one place if possible. The trigger is only here because of historical / technical reasons. Would it be possible to do it in an other way?

The node tool is central in this because it's actually the only way to access to the geometrical  Z information of vertices.

![image](https://user-images.githubusercontent.com/8614223/42813525-9a9bc75e-89c1-11e8-8d54-2cec2b6acedd.png)

As we invested a lot of time in correcting QGIS tools to handle Z correctly, I hope we will be able to use these in an intelligent way.

**Comment by m-kuhn** [comment]
Notes from the QGEP meeting. We had a discussion with local people here (including @ponceta) and @haubourg via videocall.

Presentation by @sjib : 3D Extension of VSA exists, proposal to integrate this extension


# Which Z coordinates are missing?

 - reach point geometry
 - wastewater node


# When snap to what?

 - Only at insertion
 - Snap to Z value of the wastewater node
 - Write the snapping Z value to the field on the attribute form
 - Changes to the default value should take precedence
 - Blind connections: no Z coordinate snapping

# How to deal with moving / interpolation?

 - We only do Z values on insertion

# Synchronization of Z and attribute?

 - Synchronization of attribute / Z is desirable
 - If in doubt, the attribute takes precedence
 - After digitizing, show the z($geometry) as default value for the attribute (see "when snap to what" also)

# Handling of NULL values

 - Migration script needs to take available level attributes into account and migrate to 3D geometries
 - What to use as NULL value on postgis (because apparently it's not possible to use NULL / NAN for Z)
 - Fix postgris ;P or QGIS with postgis NULL value mapping

**Comment by haubourg** [comment]
Thanks @m-kuhn !

I must admit I was wrong (never trust someone without fact checking) : NaN handling is there in PostGIS

`select st_astext( st_makepoint(1.0::float, 1.0::float,  double precision 'NaN' ))`

outputs:

`POINT Z (1 1 nan)`

SFS standards relies on IEEE 754 for doubles, that include NaN values. 

This doesn't mean that geometry manipulation functions work well, as currently mos GEOS functions just ignore Z values, but it means we could work on a QGIS provider to store NaN values in PostGIS ..

**Comment by ponceta** [comment]
Fixed in 1.2.0 (altimetry developpements)

Node, cover and reach points are not full 3D.
