### ISSUE TITLE
Missing wn_field-values in vw_qgep_wastewater_structure

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#430]
Database 1.0.1: In my testdata I have about 220 manholes (from total 1300 manholes) with no data in the wn-fields (wastewater_node). But the relation with the fk exists: if I look in the form in the wastewater nodes-tab (record is related with the relation), then the wastewater node can be modified. 
![wwns](https://user-images.githubusercontent.com/1257403/42125511-f61e8bb4-7c67-11e8-8cc7-0fc37b3f9e6e.PNG)
![wwn](https://user-images.githubusercontent.com/1257403/42125513-fd949b18-7c67-11e8-85fe-b34788044edc.PNG)
If I look in the form in the WWN-tab (data is from the wn-fields of the view), there seems to be no wastewater node.
And the other about 1080 records show the wn_field values as expected

**Comment by sjib** [comment]
@urskaufmann Is this still an issue with the latest release?

**Comment by urskaufmann** [comment]
I test next week with QGIS 3.2.2 and new datamodel

**Comment by urskaufmann** [comment]
is still the same and I still dont now whats the difference between those wastewater-structures with and without node-data in the view vw_qgep_wastewater_structure

**Comment by urskaufmann** [comment]
The problem with these records with wn_obj_id = Empty (not NULL) is, that they have a structure_part connected (e.g. access_aid or benching, covers do not count). If I delete the structure_part, then the wn_obj_id  in vw_qgep_wastewater_structure has the value that is in the database and I can work in the attribute-window as expected.
The very bad thing is: if I open the attribute window of such a wastewater_structure in edit mode and then press the OK-button, then the data (e.g. wn_identifier and wn_bottom_level and wn_remark) is set to NULL and the wn_last_modification is set to today (even there was no change at all). You lose date of the wastewaternode and dont know why!!
And the very crazy thing is: if there are more than one wastewater_nodes and a structure_part for a wastewater structure, there is also no wn_obj_id, but there is no data loss.

For me a "hors categorie" priority-bug!

**Comment by sjib** [comment]
I agree
-- 
Stefan BurckhardtAm 23.06.19, 22:26, Urs Kaufmann <notifications@github.com> schrieb:
The problem with these records with wn_obj_id = Empty (not NULL) is, that they have a structure_part connected (e.g. access_aid or benching, covers do not count). If I delete the structure_part, then the wn_obj_id  in vw_qgep_wastewater_structure has the value that is in the database and I can work in the attribute-window as expected.
The very bad thing is: if I open the attribute window of such a wastewater_structure in edit mode and then press the OK-button, then the data (e.g. wn_identifier and wn_bottom_level and wn_remark) is set to NULL and the wn_last_modification is set to today (even there was no change at all). You lose date of the wastewaternode and dont know why!!
And the very crazy thing is: if there are more than one wastewater_nodes and a structure_part for a wastewater structure, there is also no wn_obj_id, but there is no data loss.
For me a "hors categorie" priority-bug!

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ponceta** [comment]
@urskaufmann I just see this thanks to @haubourg mentionned to me.

I have the samed problem here. This is a blocker for me so top priority.
