### ISSUE TITLE
Bassin de retention construction

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#434]
How to hydraulicaly construct such a structure (in orange) knowing that the reaches don't cross the structure but stop at the entry (unlike what we can see on the plan)

![capture](https://user-images.githubusercontent.com/20111558/42326064-5641e79e-8068-11e8-9b45-bea5af6ed200.PNG)

**Comment by urskaufmann** [comment]
I am not really sure I get the functions of this structure. I think you can construct this in more than one way in the datamodel, this depends on how detailed hydraulic calculation you want to do.
You can look at this structure as one wastewaterstructure: incoming reach 500mm, outgoing reach 200/400mm, with a volume of x m3, 2 covers, one wastewater node with a throttle_shut_off_unit and hydr_geometry. In this case I don't care about the detail-hydraulic within the two manholes and the reaches 350mm. If you want to show the reaches 350mm, you draw them (2x4 reaches), but you do not connect them with fk to the node. Hydraulic thinking, they are not connected to the network and you can not automatically label the In's and Out's.  And you have now possibility to store e.g. the dimension of the manholes and separate renovation_necessity for the manholes.

**Comment by varrieta** [comment]
In the second case, why not connecting them to the node? 
I was also thinking to create 4 hydraulic node, one per reach 350mm, what do you think?

**Comment by urskaufmann** [comment]
If you want the hydraulic details, I would create
- 1. manhole with incoming reach 500 and one node
- 4 reaches (and channels) 350 between manhole and retention-tank
- special_structure retention-tank with one node and hydr_geometry
- again 4 reaches (and channels) 350 
- 2. manhole with outgoing reach and one node with throttle_shut_off_unit (and probably further elements, if there is a emergency overflow)

The 4 parallel reaches are all connected to the same nodes (if there is no prank weir or something like this).
So you have 3 (+2x4) wastewater structures, who "build" together a special function. In the first proposal, you have only one wastewater structure.

Remark: the datamodel allows you to connect the reaches to a special structure or a manhole instead of a channel, if there is for hydraulic reasons in big wastewater structures the necessity to connect two nodes. Be aware that such reaches have no connection to usage_current or function_hierarchic-fields and therefore can not by symbolized with the same stiles as "normal" (channel-)reaches.

**Comment by varrieta** [comment]
@urskaufmann Where would you place the node for the special_structure retention tank? In the middle? 
Thanks again for the explenation!

**Comment by sjib** [comment]
Same coordinate as cover or at the outlet (that's one suggestion of the [Wegleitung GEP Daten](https://www.vsa.ch/de/publikationen/shop/produkt/wegleitung-gep-daten/) for modelling)

**Comment by sjib** [comment]
@varrieta Is this solved for you? Then please close
