### ISSUE TITLE
[datamodel]  Can't create Export views

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#503]
QGEP 1.3.0 pirogue 1.0.3

I don't get any errors, but no export views are created.

I tried the hardcoded version :

`pirogue simple_joins view/export/vw_export_reach.yaml --pg_service qgep_poc`

Running `insert_export_views.sh` drops and creates `qgep_export`

Edit : Set correct pirogue version

**Comment by 3nids** [comment]
Can you update pirogue?
`pip install --upgrade pirogue`?

**Comment by ponceta** [comment]
Pirogue updated to 1.0.3, sorry, was already up to date.

We can have a look at it next thursday!

**Comment by ponceta** [comment]
@3nids I think it would be great to have these created by default on QGEP datamodel initialization. This would enable travis testing and additionnal quality insurance for pirogue and QGEP.

**Comment by 3nids** [comment]
does this solve the issue: https://github.com/QGEP/datamodel/commit/f92c67ad1dae04aeeeeca25b61839eb29970bcf5

I am 0 on adding by default. We have a few other views that are not handled at the moment. 
@m-kuhn any opinion on this?

**Comment by m-kuhn** [comment]
I think this raises an important point that we have views in the repository which are not created by default nor easy/discoverable to add.

I can see two options:

 - Add all views defined in the repo by default
 - Add a new tool that allows to easily create and load those views

The first one would be easier to do, the second one might keep schemas a bit tidier.

On the other hand, this would also be a good point in time to do some housekeeping and review what we have. What's the purpose of the export views exactly? Are they widely used?

After all, every piece of code that is inside this repository adds maintenance burden, so we need to be clear if it's worth the required resources.

**Comment by ponceta** [comment]
> @ponceta does this solve the issue: [QGEP/datamodel@f92c67a](https://github.com/QGEP/datamodel/commit/f92c67ad1dae04aeeeeca25b61839eb29970bcf5)

No, the error was not on droping nor creating the qgep_export schema.

Only on pirogue simple join returning no error and doing nothing.

I checked for pg_service issues but it's correctly set.

**Comment by 3nids** [comment]
I'm just wondering why it silently fails. I don't have any error here while creating them.

So, what could be the issue? 
1) this is not the latest version of the datamodel repo
2) this is not the last version of pirogue (unlikely)
3) there is an issue in the PGSERVICE value (maybe worth trying before running the script: `export PGSERVICE=xxxxx && ./view/export/insert_export_views.sh`
4) maybe incompatibility of pssql client/server

Some things to try:
1) create the DB using ./scripts/db_setup.sh: pirogue is also used here. Check that the views are correctly created.
2) try to use v 1.0.0 of pirogue (by downgrading): see if the script also silently fails. If not, it's an issue in pirogue's packaging
3) try to use another DB server (linux instead of windows)

I am running out of ideas here.

**Comment by ponceta** [comment]
Fixed by https://github.com/QGEP/datamodel/pull/105 and
https://github.com/QGEP/datamodel/pull/106, schema was not set and views were created in qgep_od schema.

**Comment by ponceta** [comment]
@3nids thanks for helping me fix this!
