### ISSUE TITLE
[Edition] Reaches connexion when changing only part of a reach

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#505]
I noticed that I don't know how to deal with this case :

A reach replacement is done only on some part of the reach, but no wastewater_structures are created.

`reach material`,`construction year` have to be stored since they can change.

I assume we do need to store both reaches, but then in terms of connectivity, should I set only connexion only **Reach point to** or should I create a "fake" wastewater structure (that was the "Topobase way")

![image](https://user-images.githubusercontent.com/8614223/61285491-5ea66280-a7c1-11e9-988c-1d6836871c02.png)

**Comment by varrieta** [comment]
Not sure if it is the right way, but we create hydraulic nodes in between the reach parts. And with use these nodes to do the connection.

**Comment by urskaufmann** [comment]
You have to "split" the reach (and because QGIS-split is a problem, you have to create a second reach). Because the construction year also changes, you must have two reaches and two channels afterwoods.

If the channel has function_hierarchic = pwwf (PAA , OAP) you must place a wastewater node between these two reaches. This node can be connected (fk_wastewater_structure) to one of the channels or can have NULL in this fk.  Then connect both reaches to the node. No fake wastewater structures.

If the function_hierachic = swwf (SAA, OAS), then you do not place a node or any thing else between the reaches. You just connect the reachpoint_to_fk_wastewater_networkelement of the above reach to the below reach. With that, network following works.

**Comment by ponceta** [comment]
@urskaufmann thanks for the detailled answer!

This could be useful in the documentation right?

As good practice for editing or something like that.
