### ISSUE TITLE
[datamodel] Add wastewater_node bottom_level to _label

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#509]
It would be nice to have the wastewater node elevation on the _label element of the wastewater_structure

**Comment by 3nids** [comment]
I was manually adding using the QGIS labeling tools.

This make me wonder if we are still using the best approach for labelling. These triggers are very complex and hard to maintain/adapt.
At the same time, the improvement of labelling tools and expressions (aggregates) might allow us to do these labelling manually today.

@m-kuhn thoughts?

**Comment by m-kuhn** [comment]
I agree it would be good to get this away from the database backend.

1. A check needs to be done to see what's missing
2. Possibly implement additional expression functions in QGIS if required
3. We still have a risk of performance issues because QGIS isn't as performant as the database (especially on aggregates)

**Comment by ponceta** [comment]
Having it database side is a good thing for exports and performance purposes.

As long as it doesn't slow the database as we saw with @3nids 

IMHO : 

- It should be database side
- It should be possible to disable it
- It should be executable on demand

Of course I'm never against some QGIS side optimizations for labelling.

**Comment by ponceta** [comment]
https://github.com/QGEP/datamodel/pull/112 Fix

**Comment by urskaufmann** [comment]
Whats the result if there is no value in bottom level?
For me it makes no sence to label the bottom level, if it is the same value as the out-reachpoint-level.
On the other side, if there is no detailed info about in- and out-levels, it makes no sence to label 2 or more times the same level with I= and O= . My solution till now is, not to fill in the wastewaternode-bottom level, if I have detailed reachpoint levels.

**Comment by urskaufmann** [comment]
The labeling of manholes should be easier configurable. 
This starts with the shortcuts (in German it is D, E, A, S instead of C, I, O, B).
In some cases it is necessary to add a shortcut of the function of the wastewaterstructure (because there are not symbols for every possible function).
Some people like to label the depth T=2.23  (cover level - bottom level/outlet level).

**Comment by m-kuhn** [comment]
What would be quite straightforward is fine tuning the default one according to these requirements (adding depth, additional text based on function, ...)

Changing the letters to German / French etc. is reasonably easy done too (need to add some docs for that).

Really personalizing the labels is possible, but requires an in-depth understanding of aggregate SQL. This is for most people part of the customization they need a service provider for.

**Comment by urskaufmann** [comment]
_Changing the letters to German / French etc. is reasonably easy done too (need to add some docs for that)._
In a way it's easy, but I have to do it on every new version. And because the I/O parts are sorted with the letters (not the same way as in german) it is not only changing the letters...

**Comment by m-kuhn** [comment]
I'd propose to have a look at that together later in October when I'm back in office. There are other ways which don't suffer from this (and it would be nice to add some docs for that) :)

**Comment by kandre** [comment]
Totally +1 for this issue :

At SIGE we also need to customize this _label attribute in a easy, user-friendly way. 

As I understand _label attribute in wastewater_structure  table is generated on database side through a trigger (or manually) with the general function called update_wastewater_structure_label. Modifying the function is not an option in my opinion because it will be forgotten at each model upgrade. I was opening an issue about that when I found that one.

We would like to get more control on how this _label is written, such as:
- I and O refers to input and output => users would like to see that in french (E and S)
- reorder inputs and outputs levels
- possibly add bottom_level or depth

**Comment by kandre** [comment]
@ponceta if you mind you could even rename this issue to something like "Easier customization of the _label in wastewater_structure table" as we can look for a generic solution for this issue.

**Comment by m-kuhn** [comment]
@kandre can I propose to open a new issue for this one instead?
The request here has a well defined technical solution, whereas the other one is very open.

**Comment by kandre** [comment]
@ponceta @m-kuhn yes you are right

**Comment by m-kuhn** [comment]
![Peek 2019-12-02 14-38](https://user-images.githubusercontent.com/588407/69963945-9c5a1c80-1511-11ea-9834-c93c435ce2d9.gif)
