### ISSUE TITLE
_usage_current and _fonction_hierarchic for wastewater nodes

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#530]
It could be handy for us to have 

- _usage_current
- _function_hierarchic

fields calculated for wastewater_nodes as well (maybe instead or additionnally to wastewater_structures)

**Comment by m-kuhn** [comment]
Could we just calculate it for the nodes and join it to the structures from the main node?
Or is there a risk that the main node does not have the desired usage / function hierarchic (there is a precedence involved like show the "dirtiest" and "highest hierarchy" I think)?

**Comment by sjib** [comment]
#349

**Comment by m-kuhn** [comment]
@sjib can you be more precise about your suggestions?

**Comment by sjib** [comment]
I think that taking it from the main_node is a good solutation. Therese is one case where we have to think about: "Doppelleitungen mit gemeinsamen Schacht/ Chambres et conduits doubles"
![chambre_doubles](https://user-images.githubusercontent.com/1265865/68073459-bf69a300-fd90-11e9-9b33-d764f7787f52.jpg)

The working group of the VSA of the "Wegleitung GEP-Daten / Guide des données PGEE" is suggesting in the coming release 2020 a new value "Kombischacht" for the function attribut for this case to assign instead of "Kontrollschacht / Regard_de_visit" for the main node: 

!!@ comment = "Kombischächte sind Kontrollschächte mit internem Wehr. Modelliert wird
dies mit einem Kontrollschacht (SW) und einem Leitungsknoten (RW), wobei ein
Ueberlauf_ Foerderaggregat von RW nach SW führt. Diese Verbindungen können hydraulisch
sehr grossen Einfluss haben. Hinsichtlich der Plandarstellung können Kombischschächte
(insbesondere die noch nicht sanierten) nur sehr mühsam mit einer Automatik erkannt
und symbolisiert werden. Antrag Wegleitung GEP-Daten 2020

This would allow us to add an exeption in the general rule in such a case if needed.

**Comment by urskaufmann** [comment]
If _usage_current and _function_hierachic will be taken from the main node (means from the out-going channel), then the user should be able to choose the main node (e.g. if you get data from a third part and you have to correct things). And if the main node can not be detected as discussed with the obj_id, it's not possible to export/import this information with the standard ILI.
I think this calculation of the dirtiest and highest hierachy can not be replaced.

**Comment by sjib** [comment]
@ponceta Is this solved for you?

**Comment by ponceta** [comment]
It's still an issue for us because we use wastewater nodes without wastewater structures, for slope,diameter and year changes.

![image](https://user-images.githubusercontent.com/8614223/92082675-272fb680-edc5-11ea-8224-00bdcafb6fe4.png)

We can't colorize the labels according to the passing dirtiest fluid and we can't filter entites according to the fluid type.

**Comment by sjib** [comment]
@urskaufmann Can you check this proposal?
@ponceta Will you have several pipes coming together at a slope, year or diameter change without a wastewater structure? Would that be technically correct? In the primary or the secondary system?

**Comment by ponceta** [comment]
@sjib what do you mean with technically correct? 

I would say that if it's what's in the field, then yes. But it could be technically wrong (in the sense of wastewater management), I'm no expert on that. That's why the GIS is here for right? Zoom on technical failures and issues right?

**Comment by urskaufmann** [comment]
I note, that this fields (wastewater_node._usage_current and ._function_hierarchic) are not calculated in most cases, even if I use the QGEP-tool for network connections and reconnect a reach to a node. Must entries are NULL, but most nodes are connected to from-reach_points.

**Comment by ponceta** [comment]
This should be solved with upcoming 1.6.0 release and adaptations, please feel free to reopen if needed
