### ISSUE TITLE
[audit] Replay event doesn't work

### ISSUE THREAD

**Issue by lbartoletti** [QGEP/QGEP#547]
Using https://github.com/VilleDePully/qgep_sigip/blob/master/migration/audit.sql

The replay function doesn't work

![image](https://user-images.githubusercontent.com/7521540/74341576-3fe46a80-4da8-11ea-9920-7937721b7ed8.png)

cc @ponceta @obrix

**Comment by obrix** [comment]
After an investigation it seems the last parameter uid_cols value " '{id}'::text[]" of qgep_sys.audit_view function call in audit.sql is wrong.

As the documentation says :

> Arguments:
   target_view:      TABLE name, schema qualified IF NOT ON search_path
   audit_query_text: Record the text of the client query that triggered the audit event?
   ignored_cols:     COLUMNS TO exclude FROM UPDATE diffs, IGNORE updates that CHANGE only ignored cols.
   uid_cols:         COLUMNS to use to uniquely identify a row from the view (in order to replay UPDATE and DELETE)

There is no 'id' column in the audited view, it should be replaced by 'obj_id' which seems to be the unique id of the view. This is why replay function are failing on updates. After some tests locally, replacing " '{id}'::text[]" by " '{obj_id}'::text[]" as the last parameter I managed to make the replay work.

**Comment by lbartoletti** [comment]
Ah ah. Good catch! Confirmed. It works.

@ponceta can you confirm too and take screenshot for the documentation (to have same UI), please?

**Comment by ponceta** [comment]
Screenshots are available here.

Thanks for the catch!
