### ISSUE TITLE
Parameter type layer od_file

### ISSUE THREAD

**Issue by bujard** [QGEP/QGEP#574]
Hello,

Willing to link files to reach/structure, my team had to make change regarded the type of data in the layer "od_file" where _path_relative_ should be:
![image](https://user-images.githubusercontent.com/9677103/82329909-5838d680-99e2-11ea-9a83-221682458a60.png)
 and 
_object_
![image](https://user-images.githubusercontent.com/9677103/82330001-81f1fd80-99e2-11ea-9f35-cbb394d4cae4.png).
with those parameter it's not a problem to add image or file to geometries.
Otherwise the 60 characters limits is almost guaranteed to be triggered in the _object_ field.

I know length of field is a very sensible topic but it would be nice to have more room for longer file name.

there is also a typo here: 
![image](https://user-images.githubusercontent.com/9677103/82330271-e8771b80-99e2-11ea-8995-bee33cec7170.png) (maybe someone already spotted it)

Thanks for the wonderful work on qgep. 

Regards,

s.bujard

**Comment by sjib** [comment]
How long would you like to have file path?You know that the first part of a path is put together, relative path is just the second part

**Comment by ponceta** [comment]
@bujard I think what you mentionned should not be a problem anymore if you use the vw_file instead of od_file.

**Important :** It is required to set data_media paths first. otherwise files created with this view won't be stored.

This is quite a relief since when moving full data media (on another disk / path), you just have to fix the path of the data media and not linked files.
