### ISSUE TITLE
SWMM views: Improvements

### ISSUE THREAD

**Issue by tproduit** [QGEP/QGEP#592]
According to the feedback of @DflGruBoe, the following list must be improved:
* "discharge_Coefficient_WW_current" in catchment_area doesn’t go to the suitable position in SWMM (impervious area %)
(also you could not choose which state you want to export/simulate … current or planned)
* every catchment generates a rain gates
* "vw_qgep_Abwasserbauwerk" _Beschriftung (= Name of the node) should go to the junction description in SWMM
* "vw_qgep_Haltung" Beschriftung should not go to the conduit description in SWMM
* "vw_qgep_Haltung" Lichte Höhe (= diameter) is not added in SWMM

**Comment by tproduit** [comment]
### discharge_Coefficient_WW_current

@sjib We put the value recorded in `discharge_coefficient_rw_current` in `percimperv` (impervious area %). Is it correct or should we rather use the value recorded in `discharge_coefficient_ww_current` as suggested by @DflGruBoe?

**Comment by tproduit** [comment]
### Rain gauges
Currently we create a rain gauge for each catchment area. But they are all linked to a single default time serie `default_qgep_raingage_timeserie`. The user has to add more time series if he has more rain gauges. If he has only on rain gauge then he can only update the default time serie. 
It seems to me that this workflow is the most flexible for the users. @DflGruBoe do you have another suggestion?

**Comment by tproduit** [comment]
### Junction description
Currently the description is created as follow: `(ws.identifier::text || ', '::text) || ws.remark::text AS description`. Namely, it is an aggregation of the identifier and the remark.
(We also have `wn.obj_id AS name` and `ma.obj_id AS tag`)

@DflGruBoe you suggest to remove the remark and keep only ws.identifier as the description?

**Comment by m-kuhn** [comment]
Better use `CONCAT( ..., ..., ... )` than `... || ... || ...` unless you really want the result to be `NULL` if any of the parts is `NULL`

**Comment by tproduit** [comment]
### Conduits description
Currently the description is created as follow: `(ne.identifier::text || ', '::text) || ne.remark::text AS description,`. 

@DflGruBoe Similarly, to the issue above you suggest to remove the remark and keep only ws.identifier as the description?

**Comment by tproduit** [comment]
> 
> 
> Better use `CONCAT( ..., ..., ... )` than `... || ... || ...` unless you really want the result to be `NULL` if any of the parts is `NULL`

Thanks for the advice! Indeed, ws.remark is often NULL and then the SWMM description is NULL.

**Comment by tproduit** [comment]
### Conduit diameter
I found the problem I will solve it.

**Comment by sjib** [comment]
> ### discharge_Coefficient_WW_current
> @sjib We put the value recorded in `discharge_coefficient_rw_current` in `percimperv` (impervious area %). Is it correct or should we rather use the value recorded in `discharge_coefficient_ww_current` as suggested by @DflGruBoe?

Impervious area is more a rain water thing and not a wastewater issue. I think it is correct, else I would need more arguments.

**Comment by DflGruBoe** [comment]
> ### discharge_Coefficient_WW_current
> @sjib We put the value recorded in `discharge_coefficient_rw_current` in `percimperv` (impervious area %). Is it correct or should we rather use the value recorded in `discharge_coefficient_ww_current` as suggested by @DflGruBoe?

"discharge_coefficient_rw_current" is fine for us

**Comment by sjib** [comment]
Urs gave me a good hint, that we have to consider, whether we are running a calculation for a current status or planned status: 

We have up to four relations in a catchment that relate to up to four different wastewater structures: fk_rw_current / fk_ww_current for the current status and fk_rw_plannend and fk_ww_planned for the planned status. So we have to check in a wastewater structure which foreignkeys are set and then get either discharge_coefficient_rw_current (if we have a seperated system and a rainwater wastewater structure or we have to calculate the percimperv from the wastewater and the rainwater part if we have a mixed system).

Also we have to consider, that from the view point of a node, there could be several different catchments attached. 

So I think we have to check whether the link to the wastewater_structure (in SWMM the junction) is already set right:

> coalesce(fk_wastewater_networkelement_rw_current, replace(ca.obj_id, ' ', '_')) as Outlet,

and whether we need also the wastewater catchments contribution and would need to UNION the current part with a second part with the wastewater (ww). This would then may be also need an adaption of the Name attribut with a suffix rw and ww

`SELECT
  replace(ca.obj_id, ' ', '_') as Name,
  ('raingage@' || replace(ca.obj_id, ' ', '_'))::varchar as RainGage,
  coalesce(fk_wastewater_networkelement_ww_current, replace(ca.obj_id, ' ', '_')) as Outlet,
  CASE
    when surface_area is null then st_area(perimeter_geometry)
    when surface_area < 0.01 then st_area(perimeter_geometry)
    else surface_area
  END as Area,
  discharge_coefficient_ww_current as percImperv, -- take from catchment_area instead of default value
  CASE
    WHEN wn.situation_geometry IS NOT NULL
    THEN 	
    (
    st_maxdistance(wn.situation_geometry, ST_ExteriorRing(perimeter_geometry))
    + st_distance(wn.situation_geometry, ST_ExteriorRing(perimeter_geometry))
    )/2
    ELSE
    (
    st_maxdistance(st_centroid(perimeter_geometry), ST_ExteriorRing(perimeter_geometry))
    + st_distance(st_centroid(perimeter_geometry), ST_ExteriorRing(perimeter_geometry))
    )/2
  END as Width, -- Width of overland flow path estimation
  0.5 as percSlope, -- default value
  0 as CurbLen, -- default value
  NULL::varchar as SnowPack, -- default value
  ca.identifier || ', ' || ca.remark as description,
  ca.obj_id as tag,
  ST_Simplify(ST_CurveToLine(perimeter_geometry), 5, TRUE)::geometry(Polygon, %(SRID)s) as geom
FROM qgep_od.catchment_area as ca
LEFT JOIN qgep_od.wastewater_networkelement we on we.obj_id = ca.fk_wastewater_networkelement_ww_current
LEFT JOIN qgep_od.wastewater_node wn on wn.obj_id = we.obj_id
WHERE fk_wastewater_networkelement_ww_current IS NOT NULL; -- to avoid unconnected `

What do you think? 
Do you have significant runoff in the mixed system that comes from wastewater catchments? What is the default value for this in SWMM in comparison?

**Comment by urskaufmann** [comment]
As I mentioned to Stefan:
First of all, the sewage network to be calculated must be determined. And the user chooses whether a calculation is made for the current state or for the planning state.
With these definitions the rest is given: The wastewater nodes are determined. All catchment areas with a foreignkey to a selected wastewater node must be taken into account. Which attribute (discharge coefficient, seal factor) is adopted is determined by the link to the wastewater node. A catchment area can be taken over twice if e.g. both wastewaternode-foreignkeys are defined in the current state (separated system or modified system).

**Comment by m-kuhn** [comment]
Current vs. planned: should this be an option in the processing algorithm?

**Comment by urskaufmann** [comment]
> Current vs. planned: should this be an option in the processing algorithm?

I do not know SWMM and if SWMM can handle different states. But in a hydraulic calculation you can not mix planned and current. I think the user must have this option (the same for other programmes like mikeurban).

**Comment by m-kuhn** [comment]
>  think the user must have this option (the same for other programmes like mikeurban).

@tproduit / @DflGruBoe  forwarding this question then: at what point should the user select this?

 a) when launching the processing algorithm
 b) should processing export both and is this then selected somehow inside swmm

**Comment by sjib** [comment]
I would suggest to select it to select it at the very beginning and to make for all views we have  a *_current and a *_planned version. This would allow to add a simple parameter at the beginning to add in the code an it could run thru the same way for both cases.

**Comment by sjib** [comment]
@tproduit Your first fixes seem to have been added to master now. Can you confirm and check?

**Comment by sjib** [comment]
@tproduit Can you work on the option current vs. planned now and check with @DflGruBoe how quickly they would need that?

**Comment by tproduit** [comment]
> 
> 
> @tproduit Your first fixes seem to have been added to master now. Can you confirm and check?

@sjib My last merge request is not merged yet. I saw that @m-kuhn did some changes in the swmm_views (descriptions), which will solve some issues.

**Comment by tproduit** [comment]
> 
> 
> @tproduit Can you work on the option current vs. planned now and check with @DflGruBoe how quickly they would need that?

@sjib @DflGruBoe I can work on it these next week and create a merge request for mid-november. Would it fit for you? @sjib I will come back to you to plan a remote meeting, I will probably have some questions for you once that I will have start to work on it.

**Comment by sjib** [comment]
@tproduit @m-kuhn Would be great to have all issues fixed for QGEP/datamodel#147 as @DflGruBoe needs the tool to simulate data in SWMM in current projects and is waiting for it.
