### ISSUE TITLE
qgep_od.vw_network_xx replaced by qgep_network.xx

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#593]
When using PUM for versioning, the 2 materialized views vw_network_node and segment aren't deleted from the qgep_od schema. Shouldn't they be?

Also, the projet qgep.qgs is still using the materialized views from qgep_od and not the one from qgep_network schema.

**Comment by olivierdalang** [comment]
@varrieta 
This is expected, but the views have changed and use the qgep_network tables now. It was made this way so that the plugin (and the qgs project) could continue working without almost no change.

In the future though we'll be able to drop them and simplify the plugin (see https://github.com/QGEP/QGEP/issues/568)

**Comment by olivierdalang** [comment]
(feel free to reopen if needed)
