### ISSUE TITLE
Automatical fill in of reach point identifier

### ISSUE THREAD

**Issue by varrieta** [QGEP/QGEP#621]
When a reach_point correspond to a wastewater_node, the rp_identifier isn't automatically filled in with the node identifier.
Is there a reason or could we automatize that ? 

ps: I thought there was already an issue about that but I couldn't find it. My bad if it does exist!

**Comment by m-kuhn** [comment]
Would that work, given that there can be multiple rp per node and identifier is unique?

**Comment by sjib** [comment]
I would rather suggest to use the reach name (e.g. 123-124) to name the two reach_points e.g. add an A for Anfang / begin at the beginning: 123-124A and 123-124E (E for Ende / end). I know this is language based A and E, in French it would be ?? and ??. In English S (start) and E (end). 
And we get a problem if the reach identifier is already 20 characters long.

@urskaufmann Any other ideas?

**Comment by urskaufmann** [comment]
As Matthias says: will not work, because identifier is unique.
My solution (is also in the project template): set the rp_from_identifier = reach - identifier+"F" as default and the rp_to_identifier = reach - identifier + "T" (From/To). (And the reach identifier = reach obj_id). 
[image](https://user-images.githubusercontent.com/1257403/105136752-7a936e80-5af2-11eb-8dad-2acea93f0d84.png)

**Comment by varrieta** [comment]
I prefer sjib solution because with the reach obj_id you don't see quickly which node it is linked to (since the label display the node identifier and not the obj_id)

But indeed this can be manage in the project defaults values. For me the post can be closed.
