### ISSUE TITLE
Moving wastewater_structures or nodes

### ISSUE THREAD

**Issue by urskaufmann** [QGEP/QGEP#630]
The behaviour when moving a wastewater structure, a node or a cover is no more the same as described in the docu chapter 2.3.2. With the node tool (all layers) I can move only points in the active layer. Can someone confirm?.

Other question: when I move a wastewater node in a manhole with just one node, should then not also the point in vw_qgep_wastewater_structure move to the new location? Because this point has the location of the main-node? Why does he not move?

**Comment by ponceta** [comment]
To my knowledge, mutli layer node edit will edit the elements it catch first (if your wastewater layer is on top of your cover and node, this will be your ws layer almost every time (EVEN if you are on the cover or node layer))

Since layer referencing is not set in the demo project we still need to make some adjustments to the qgs project.

Actually if you try to move a node or a wastewater structure or a cover, the database will do the translation but qgis will only interpret it visually.

![image](https://user-images.githubusercontent.com/8614223/106863331-a30d9200-66c8-11eb-96a4-bb4dbd7799d4.png)

Since QGIS 3.12 I think we can set circular dependencies meaning QGIS will listen to the modifications from a layer to another and vice-versa. (ws->node and cover, node ->ws, cover -> ws and maybe a link is needed on reaches and reach points too)

![image](https://user-images.githubusercontent.com/8614223/106863360-b0c31780-66c8-11eb-9cf9-24bbff3cd035.png)

This set, if you move the main node of your wastewater structure should move accordingly.

But be generally careful when moving connected objects because qgep has additionnal db mechanics which moves objects together (especially wastewater structures)

![Node_moving](https://user-images.githubusercontent.com/8614223/106863981-95a4d780-66c9-11eb-86a6-0b5d48aad944.gif)

**Comment by ponceta** [comment]
Not an issue anymore on QGIS 3.16.X and latest qgep project.
