### ISSUE TITLE
Adjust qgs Project File and Demodata to version 1.5.4 or newer

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#643]
Add additional elements to project: 

- [ ] [vw_catchment_area_connections.sql](https://github.com/QGEP/datamodel/blob/master/view/vw_catchment_area_connections.sql)
- [ ] [vw_qgep_maintenance_on_reach.sql](https://github.com/QGEP/datamodel/blob/master/view/additional_views/vw_qgep_maintenance_on_reach.sql)
- [ ] [vw_qgep_maintenance_on_wws.sql](https://github.com/QGEP/datamodel/blob/master/view/additional_views/vw_qgep_maintenance_on_wws.sql)
- [ ] New views and forms for adding overflow elements (leaping_weir, pumps, ...)
- [ ] Add description fields in forms [#645 ](https://github.com/QGEP/QGEP/issues/645)
- [ ] Other new views or layers that members created? - Please add here

- [ ] Export missing text for current plugin version
- [ ] Export missing text from project to Transifex to be translated
- [ ] Reimport to language files
- [ ] Deploy new project file

Demodata

- [ ] Add hydraulic demodata such as pumps and weirs
- [ ] Add some VSA-KEK data (a few examples) including pictures and 1-2 videos
- [ ] ...

**Comment by urskaufmann** [comment]
Both vw_qgep_maintenace_on_reach/wws.sql have a problem (I think with the geometry-field) and should by granted to qgep_user instead of qgep). If the views are in the datamodel, I can take them in the project file.

vw_catchment_area_connections are now just defined for the two current cases, not for the planned cases. I prefer to have additional information (length of the connection line) to find out the real long distances (that may be errors).

**Comment by urskaufmann** [comment]
The problem a mentioned with vw_qgep_maintenace_on_reach/wws.sql is my primary-key-field. If I uncheck the option to Check PK unicity while adding the layer to the project, it works even with my numeric obj_id-field.
Is this a problem?
