### ISSUE TITLE
QGIS 3.28.1 Bug on inserting manually altitude to reach points

### ISSUE THREAD

**Issue by ponceta** [QGEP/QGEP#779]
**Describe the bug**
Manual update on reach points altitude seems to fail on newer versions of QGIS (tested on QGIS 3.28.1)

**To Reproduce**
Exact steps to reproduce the behavior:
On QGIS 3.28.1
1. Create new Reach
2. Set reach point from altitude
3. Set reach point to altitude
4. Error : Reach point from altitude is set to NULL

**Expected behavior**
Manual editing of reach points altitude is possible through the vw_qgep_reach layer. (like on QGIS 3.22)

**Screenshots / data**
![Reach_points_altitude_update_impossible](https://user-images.githubusercontent.com/8614223/205877990-438a768b-68fb-4e7d-8dd2-1fcf6c2a4e8c.gif)

**Python scripts on reach point from and to :**

```
with_variable(
   'snapped_result',
   array_first(@snapping_results), if(map_get(@snapped_result,'valid')=true, 
   attribute(get_feature_by_id(map_get(@snapped_result, 'layer'), map_get(@snapped_result, 'feature_id')), 'obj_id'),NULL))
```

```
with_variable(
   'snapped_result',
   array_last(@snapping_results), if(map_get(@snapped_result,'valid')=true, 
   attribute(get_feature_by_id(map_get(@snapped_result, 'layer'), map_get(@snapped_result, 'feature_id')), 'obj_id'),NULL))
```

**Desktop (please complete the following information):**
 - QGEP plugin version
 - QGEP datamodel version
 - QGEP project file version
 - QGIS Version 3.28.1
 - OS

**Additional context**

**Comment by PeterZamudio** [comment]
Hello everyone
I did the test and I must say I do not have the same problem. I did the test first with QGIS 3.28.1 and QGEP-Plugin 1.5.5. It worked perfectly. I then updated the QGEP-Plugin to version 1.5.6-b9 and tested again. The tests were first 2 wastewater structures and then a reach digitized. I encounted no problems and the start and end heights were entered and saved.
![QGEP_Test_PZa](https://user-images.githubusercontent.com/32352291/207534152-c6aff471-1b53-44f7-b295-6b0551d8dbec.jpg)

**Comment by PeterZamudio** [comment]
When I look closely at your video, I notice you have altered the configuration of the field. When I enter the height I have that problem with the point and have to press arrow right in stead of decimal. We have discussed this in the group. I see you have changed the configuration and the problem might be there too.

**Comment by ponceta** [comment]
When changing the **rp_from_level** and **rp_to_level**

**Comment by PeterZamudio** [comment]
Thank you, I am just saying your problem might be because you have apparently changed the standard settings.
I haven't changed anything and it still seems to be working as it was before 3.28.1. I am talking about the problem you have and not the decimal problem.

**Comment by ponceta** [comment]
The decimal problem is present in qgep project when changing from range to text widget. (QGIS 3.22->3.28.2)

This is due to the fact that the co_level or rp_from_level and rp_to_level are displayed at multiple places in the form (general + specific tab)

![altimetry](https://user-images.githubusercontent.com/8614223/211283918-a3fd5b60-b8d8-4e46-a698-0ece1e16da65.gif)

**Comment by olivierdalang** [comment]
I think that the second part (about the decimals) is the same as https://github.com/QGEP/QGEP/issues/749, which we reported upstream already.

@ponceta is the first part of the issue (about altitude being set to NULL) still relevant ? If no, we can close this, if yes, could you edit/remove your comments about the second part just so that it's clear what this is about ?

**Comment by ponceta** [comment]
@olivierdalang this is a critical issue for us in Pully and we have to look at it and solve this before QGIS 3.28.4 release.

**Comment by olivierdalang** [comment]
@ponceta Not sure I get this right. Here I'm not able to reproduce the issue with the QGEP project (neither with the digitize tool nor with the wizard). As pointed out by Peter, it seems you're not using the standard form ?

Can you provide steps on the demo data/project to reproduce ?

If not in the demo project, but indeed on customizations of yours, can you provide a reproduceable case (a QGIS project, ideally with data), including full info on QGIS version ? (but in that case, should we really track that issue here in the QGEP tracker ?)

It's not really possible otherwise to work on this, because there could be many things involved (once again the the input being present multiple times in the form, some QGIS bug in one of the functions used in your python expression, the python expression themselves, etc.)

**Comment by ponceta** [comment]
Here's the qgep project with updated fields and type as it will be in qgep future .qgs project :

[qgep.zip](https://github.com/QGEP/QGEP/files/10478562/qgep.zip)

I will list modifications in the right issue.

There is a QGIS issue with python default values for fields :

![QGEP_rp_from_to_fields_demo](https://user-images.githubusercontent.com/8614223/214012619-eb4b4451-e02a-4676-bf12-5ecbd875f748.gif)

Python actions are called on every field update instead of only at the opening of the form even if the update default is not checked :

![image](https://user-images.githubusercontent.com/8614223/214013074-c5a0b0f4-d450-4bf9-9e04-5c559bc688ec.png)

There's a problem hidden in QGIS that will break many .qgs projects using default "editable" values.

**Comment by ponceta** [comment]
QGIS upstream issue.

**Comment by olivierdalang** [comment]
fixed by https://github.com/qgis/QGIS/pull/51836

**Comment by ponceta** [comment]
QGIS Minimal version for this seems to be 3.30.0. This really needs a backport.

**Comment by ponceta** [comment]
Integrated in QGIS 3.28.4-2! Installed and tested with osgeo4w, work as expected!
