### ISSUE TITLE
Handling of fk_dataowner and fk_provider

### ISSUE THREAD

**Issue by cymed** [QGEP/QGEP#814]
**Describe the bug**
At the moment, both qgep_od.wastewater_networkelement and qgep_od.wastewater_structure have the attributes fk_dataowner and fk_provider. vw_qgep_reach uses the network element only, while vw_qgep_wastewater_structure uses both. We should eliminate the fk in wastewater structure as the information is redundant. However, I do not know the dependencies for qgepqwat2ili and other processes

**Comment by sjib** [comment]
qgepqwat2ili only copies the data stored in the od tables.

So this is a general taks we should solve and not a bug but rather an enhancement on dealing with the metaattributes in TEKSI.
fk_provider makes only sense on channel

@urskaufmann I know you mentioned already about this. Do you have suggestions how to improve this? E.g. fk_dataowner of channel / reach should always be set the same.

**Comment by urskaufmann** [comment]
I am not happy with this dataowner and provider for every (super)class in the dss-model. The "correct" way to emplement this would be a relation between  organisation(dataowner) / organisation(provider) for every class (means more than 150 relations only for dataowner and provider). But in 99,x% you will not want to spend time with this attributes.
Classes like reachpoint, profile_geometry or surface_runoff_parameter should always have the same dataowner / provider as there reach / pipe_profile / catchment_area, because they don't exist without reach or pipe_profile....
I think it makes not sense, that wastewater_structures and there networkelement or there structure_parts have different dataowner or provider. If the wastewater_structure dies, the related records will die also, no matter if the dataowner is equal or not.
My proposal: we define in qgep_sys a default dataowner and a default provider. Every record get's this defaults, when we create a new record. When we get third-part data, the dataowner and provider should be already set.
And there should be a simple way to change dataowner and provider e.g. with a tool (not with the standard form window). For selected records in one class.  And also with search/replace function over all classes.

**Comment by cymed** [comment]
> I think it makes not sense, that wastewater_structures and there networkelement or there structure_parts have different dataowner or provider. If the wastewater_structure dies, the related records will die also, no matter if the dataowner is equal or not. 

The simplest way is to implement it on network element only, and to use inheritance to set the parameter elsewhere. 

>My proposal: we define in qgep_sys a default dataowner and a default provider. Every record get's this defaults, when we create a new record. When we get third-part data, the dataowner and provider should be already set. And there should be a simple way to change dataowner and provider e.g. with a tool (not with the standard form window). For selected records in one class. And also with search/replace function over all classes.

Our current solution in the office is to set the fk_dataowner and fk_provider on the QGIS side via variables.

**Comment by sjib** [comment]
I think this needs some thoughts and needs also to consider fk_owner / fk_operator:

- I think in most (?) cases the fk_owner defines also the fk_dataowner
- fk_operator is mainly dependend from how the municipality works together with the wastewater association
- fk_provider I think is reflecting the decisions taken in the Datamanagement concept of a GEP

| Use case                                                                                                                                                                                                                 | fk_owner (Eigentümer) | fk_operator (Betreiber) | fk_dataowner (Datenherr) | fk_provider (Datenlieferant)            |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|-------------------------|--------------------------|-----------------------------------------|
| **Network data** (_just channel / manholes or also reach, reach point, wastewater node?_)                                                                                                                                      |                       |                         |                          | _Defined in the data management concept_  |
| Network data of community                                                                                                                                                                                                | Gemeinde_X            | Gemeinde_X              | Gemeinde_X               | Katasterbüro K                          |
|                                                                                                                                                                                                                          | Privat                | Gemeinde_X              | Gemeinde_X               | Katasterbüro K                          |
|                                                                                                                                                                                                                          |                       |                         |                          |                                         |
| Network data of wastewater_association                                                                                                                                                                                   | Abwasserverband_Z     | Abwasserverband_Z       | Abwasserverband_Z        | Katasterbüro I                          |
|                                                                                                                                                                                                                          |                       |                         |                          |                                         |
|                                                                                                                                                                                                                          |                       |                         |                          |                                         |
| Network data of community that has outsourced network management to wastewater association                                                                                                                               | Gemeinde_X            | Abwasserverband_Z       | Abwasserverband_Z        | Katasterbüro J                          |
|                                                                                                                                                                                                                          | Privat                | Abwasserverband_Z       | Abwasserverband_Z        | Katasterbüro J                          |
|                                                                                                                                                                                                                          |                       |                         |                          |                                         |
| Strassenentwässerung Kantonsstrassen                                                                                                                                                                                     | Kanton_A              | Kanton_A                | Kanton_A                 | Kanton_A or Katasterbüro L              |
|                                                                                                                                                                                                                          |                       |                         |                          |                                         |
| **Other information**                                                                                                                                                                                                        |                       |                         |                          |                                         |
| Hydraulic information (_define which ones - reach, reach point, wastewater node or only additional hydraulic elements not directly connected to channel / manholes as pumps, weirs, absperrdrosselorgan, kennlinien) etc._ |                       |                         | Gemeinde_X               | GEP Ingenieur or Hydraulic specialist H |
| Catchment areas                                                                                                                                                                                                          |                       |                         | Gemeinde_X               | GEP Ingenieur or Hydraulic specialist L |
| Log cards (Stammkarten)                                                                                                                                                                                                  |                       |                         | Gemeinde_X               | GEP Ingenieur or Hydraulic specialist M |
| Biol_ecol_assessment (Biologisch ökologische Gesamtbeurteilung)                                                                                                                                                          |                       |                         | Gemeinde_X               | Biologe B                               |
| TV inspection data                                                                                                                                                                                                       |                       |                         | Gemeinde_X               | Kanalfernsehfirma F                     |

Two options for Network data

- [ ] just channel / manholes
- [ ] or also reach, reach point, wastewater node

and connected with this:
Hydraulic information

- [ ] only additional hydraulic elements not directly connected to channel / manholes as pumps, weirs, absperrdrosselorgan, kennlinien) etc._
- [ ] or all hydraulic elements including each, reach point, wastewater node

@urskaufmann @cymed What do you think?

Are there more use cases?

**Comment by cymed** [comment]
The key question is where we have unnecessary duplicates. apart from the classes that are no longer in VSA DSS, the following classes have a fk_provider

- catchment_area
- connection_object
- control_center
- damage
- data_media
- file
- hq_relation
- hydr_geom_relation
- hydr_geometry
- hydraulic_char_data
- maintenance_event
- measurement_result
- measurement_series
- measuring_device
- measuring_point
- mechanical_pretreatment 
- mutation
- organisation
- overflow
- overflow_char
- pipe_profile
- profile_geometry 
- reach_point
- retention_body 
- sludge_treatment
- structure_part 
- surface_runoff_parameters
- throttle_shut_off_unit
- txt_symbol
- waste_water_treatment
- wastewater_networkelement
- wastewater_structure
- wastewater_structure_symbol
- wwtp_energy_use
- zone

pipe_profile, profile_geometry, reach_point ,structure_part and wastewater_structure should, in my opinion be managed through the wastewater_networkelement.

**Comment by urskaufmann** [comment]
Use cases: normally I am very happy, if the owner is 100% clear for each wastewater_structure. And normally, the owner is also the  operator (means normally I have no other infos or no info at all about the operator).  I have just one association that is operator for the community and I know one association that is operator also for private structure.
Normally, records with the same obj_id-prefix will have the same dataowner and the same provider.

Managed through networkelement: Nobody except this GEP-nerds talks about networkelements. But because QGEPs-mainlayer are build with the networkelements, it's in QGEP propably the best way to manage it with the networkelements (main-layers). Means: the value defined in the mainlayer is copied to wastewater_structure, to all structure-parts, to reachpoints, to other networkelements (that are not main node). There is one little theoretical problem, if we have have two or more reaches with the same channel and we define different metaattributes....

Pipe-profile: is not managed from networkelement. Profile-geometry is managed from pipe-profile.

Overflows and hydr_Data: not sure. Can I delete a special_structure, if there is an overflow with a third-part-dataprovider. What are the wright's of someone who is not dataprovider?

Catchment_area and connection_object: separate dataprovider possible.

TV Inspection, bio_oecl_assessment: I think the TV-Firma is not dataprovider, they are in maintenance_event.fk_operating_company. Normally it's the GEP-Ingenieur. re_maintenance_event_wastewater_structure and examination are managed by maintenance_event. 

KEK-classes, file and data_media?
Measuring-classes: ?
Stammkarten: GEP-Ing.

**Comment by sjib** [comment]
Implemented option to set default fk_* implemented in TEKSI wasteater https://github.com/teksi/wastewater/pull/173
