### ISSUE TITLE
Wizard new reach Error creating new reach without rp_levels

### ISSUE THREAD

**Issue by sjib** [QGEP/QGEP#821]
**Describe the bug**
Error when creating new reach with wizard without rp_levels (from and/or to)

**To Reproduce**
Exact steps to reproduce the behavior:
1. Go to 'Wizard'
2. Click on 'Start Data Entry' and then 'Reach'
3. Create new reach and try to save

**Expected behavior**
No geometry errors should appear

**Screenshots / data**
![20230621_new_reach_wizard_progression_geometry_error](https://github.com/QGEP/QGEP/assets/1265865/20e619cc-64db-4f95-828c-68e13cf314c0)

**Desktop (please complete the following information):**
 - QGEP plugin version 1.6.1
 - QGEP datamodel version Demoproject
 - QGEP project file version 
 - QGIS Version 3.26.8
 - OS Linux
 - Postgis 3.3

**Additional context**
Feedback von @cymed: Ich hatte den Fehler soeben auch, allerdings nur, wenn ich keinen rp_from_level oder rp_to_level hatte. Habe danach ein Experiment gemacht. Anscheinend funktioniert ST_SetPoint in der Test-DB nicht mit NaN-Werten in den zu setzenden Koordinaten (Postgis 3.3)…

Feedback von @sjib I do not have the error on Windows / QGIS 3.28.4 and Postgis 3.0

**Comment by sjib** [comment]
@cymed I hope this is now correct - I transfered this to a new issue.

**Comment by ponceta** [comment]
> @ponceta Meanwhile, which PostGIS version would you recommend ?
> 
> The PostGIS version should be added to https://github.com/teksi/Home/wiki/TEKSI-modules-releases-and-roadmap

3.2 is tested and Works fine, I'll add it to the Release versions table!

**Comment by cymed** [comment]
Is this an issue to address upstream on PostGIS-Side?

**Comment by ponceta** [comment]
> Is this an issue to address upstream on PostGIS-Side?

I don't think so, it is probably some old postgis functions used in QGEP which need a technological update/upgrade.

**Comment by cymed** [comment]
> > Is this an issue to address upstream on PostGIS-Side?
> 
> I don't think so, it is probably some old postgis functions used in QGEP which need a technological update/upgrade.

ST_SetPoint is still officially supported, see [https://postgis.net/docs/manual-3.4/en/ST_SetPoint.html](https://postgis.net/docs/manual-3.4/en/ST_SetPoint.html) from the 3.4 manual

**Comment by Kay-Korrodi** [comment]
I have since 3 Days  the same problem. We cant build a new Line or replace it without a high in it.
We found a solution we are trying atm: https://github.com/teksi/wastewater/issues/20
it says if you install de dev version 3.4.2 or 3.5.0 you can fix the problem with Null and NaN. Has anybody try it out?

**Comment by ponceta** [comment]
From @3nids, @Kay-Korrodi have you any ways to test it on upgraded versions?

> It seems the bug has been fixed in 3.2.7
> https://postgis.net/docs/manual-3.2/release_notes.html#idm43481
> 
> and 3.4.2 too

I'll have a look at it here too.

**Comment by sjib** [comment]
@Kay-Korrodi Can you share your're experience with installing 3.4.2 / Kannst du teilen, wie die Installation von 3.4.2 funktioniert hat? Gibt es irgendwelche Hürden zu beachten?

**Comment by Kay-Korrodi** [comment]
Hey @sjib Hey @ponceta 

E: The Update to 3.4.2 worked with no problem
D: Das Update auf 3.4.2 ging ohne Probleme

E: All dbs except qgep could be updated using the command. For QGEP we deleted under Extension / postgis and reinstalled it
D: Über den Befehl konnten alle dbs ausser qgep upgedated werden. Bei QGEP haben wir unter Erweiterung / postgis gelöscht und neu installiert

C: SELECT PostGIS_Extensions_Upgrade();

E: Everything has been running without errors for 1 week and the bug is fixed with the update
D: Seit 1 Woche läuft alles ohne Fehler und der Fehler ist behoben.

E: If you have any further questions, please do not hesitate to contact me 
D: Bei weiteren Fragen stehe ich gerne zur Verfügung
