### ISSUE TITLE
manhole/cover venting

### ISSUE THREAD

**Issue by 3nids** [QGEP/QGEP#85]
It seems that the venting information is related to the cover and not to the manhole.

For my colleagues, this seems incorrect. They say the venting is a pipe that starts from the manhole.

What do you think?
@sjib any feddback?

**Comment by urskaufmann** [comment]
Wonder, if i can answer at this mail…

Lock at the two pictures for the meaning of the field cover – venting.
The venting-pipe (Entlüftungsrohr) is something special with primary wastewater-structures. I think vou have to model as
Kanal with Nutzungsart = other.



Von: Denis Rouzaud [mailto:notifications@github.com]
Gesendet: Donnerstag, 12. März 2015 09:07
An: qgep/QGEP
Betreff: [QGEP] manhole/cover venting (#85)


It seems that the venting information is related to the cover and not to the manhole.

For my colleagues, this seems incorrect. They say the venting is a pipe that starts from the manhole.

What do you think?
@sjib<https://github.com/sjib> any feddback?

**Comment by 3nids** [comment]
![image](https://cloud.githubusercontent.com/assets/127259/6614424/48b907c6-c89a-11e4-9252-df77c761a9fc.png)
![image](https://cloud.githubusercontent.com/assets/127259/6614426/4eae5636-c89a-11e4-8556-d3b69ee48e8b.png)

**Comment by 3nids** [comment]
Thanks Urs for the feedback.

**Comment by m-kuhn** [comment]
Is there a conclusion on this topic?

**Comment by andreasneumann** [comment]
no idea - the waste-water experts need to answer this.

Perhaps there are two type of venting?
The venting holes in the cover (meant in this context) and the special venting with a venting pipe (more rare then the other case)?

**Comment by sjib** [comment]
Here a feedback from urs that I translate about the attribution rules (text in German and English):

also diese Lüftungsrohre:
Deine Links betreffend den Sanitär (Gebäudeentwässerung). Da wir ja mit den Siphons (wegen Geruchsverschluss) eine Luftbarriere haben in der Entwässerung ist eine Entlüftung im Gebäude notwendig (sonst gibt es Geruchsprobleme). Aber dieses Leitungen kommen nicht in den WI.
http://www.sbz-online.de/SBZ-2011-21/Druckausgleich-in-der-Abwasserleitung,QUlEPTMzNDMzNyZNSUQ9MTAxOTAy.html
There are venting pipes in buildings - they need a siphon because of airing - but this is not part of the waste water system

Dann gibt es selten noch Lüftungsrohre bei Spezialbauwerken wo die Gefahr des Zuschlagens der Leitung besteht. ZB. bei Leaping Wehren, bei Steilleitungen, Fallsträngen, Wirbelfallschächten. Wenn möglich macht man ja die Belüftung über belüftete Deckel. Oder im Bauwerk intern. Dann gibt es aber Speziallfälle, wo man keine belüfteten Deckel wünscht (zB beim Schlittelweg Mürren - Gimmelwald, der isolierte Deckel hat, damit der Schnee schön bleibt und Isolierung und Belüftung passen nicht zusammen).

Then there are venting pipes at special structure, where you could have a blocking of the water flow when there air could not pass by eg. leaping weirs, steep channels, Fallsträngen, Wirbelfallschacht.
If possible airing goes thru covers, but this is not always possible.

Wenn ein solches Lüftungsrohr im Erdreich verlegt wird, dann sollte man es wohl schon im WI erfassen (bauliche Dokumentation). Die Attribute sind dann meistens "andere" (Nutzungsart, Funktionhydraulisch, ...). Aber die sind wirklich selten.

If such an airing pipe needs to be added then you want to add it into your WI information (documentation of buildings).
Use the following attributes: Nutzungsart (usage_*) = other, FunktionHydraulisch (function_hydraulic) = other, FunktionHierarchisch (function_hierarchic) = other

Trockenwetterfallrohre sind ja Bauteile und in aller Regel unterhalb dem normalen Kanal, also kann man das im WI auch praktisch nicht darstellen (= modellieren wir nicht).
Then there are dryweather_downsprout - usually below the normal channel, this is difficult to visualize and I do not model it (but you could do the same way as venting pipes with "other")
