### ISSUE TITLE
remark fields are too short

### ISSUE THREAD

**Issue by 3nids** [qgep/QGEP#86]
text is limited to 80 char which I think is too small.
OK to increase?

How do we proceed for such changes?
Can I modify the SQL or is @sjib suppose to proceed?

**Comment by sjib** [comment]
No, do not change. It is limited so that people store information in given attributes and not as comments. If they need more space we have to think about new attributes.

**Comment by 3nids** [comment]
ok! I find it quite restrictive though. I'll try to import the whole data and see where the troubles come from.

**Comment by tudorbarascu** [comment]
Hi guys,
I also stumbled on this issue while trying to import data from another model that has quite a lot written in the remarks section.
IMHO I think it would be better to increase the size of the field in order to ease up migration process for newcomers to QGEP that have a lot written in the remarks section.
Otherwise, I believe we would unwillingly extend the time taken for migrations as parsing 20k remarks while trying to fit them in the data model is certainly taking a big toll on the migration time.
Although workarounds exists and Stefan has a good point I feel that the advantages dwarf the disadvantages.

**Comment by sjib** [comment]
Then I suggest to add a tempory remarks field to the classe where you have too long remarks to import those long remarks that contain data, that should be merged to other fields. It is an important step to improve data quality to get rid of all remarks that have to be filled into existing attributes.

.  <https://github.com/notifications/beacon/ABNQyXIenl_CT5o7OK6pnaL3LxsH0q8Eks5opsMlgaJpZM4Dtg3G.gif>

**Comment by tudorbarascu** [comment]
Thanks for the comments Stefan, was doing just that as a workaround.
